import { describe, it, expect, beforeEach, vi } from "vitest"

/**
 * Security-critical: these helpers enforce the access model for
 * every Junebug route. A regression here could leak another user's
 * thread data to a caller.
 *
 * We mock the three dependencies (feature flag, NextAuth session,
 * Prisma) to test the gate logic in isolation. Integration tests
 * against a real DB live elsewhere.
 */

// Mock modules before importing the subject. Vitest hoists these
// mocks above the imports so the real implementations never load.
vi.mock("./feature-flag", () => ({
  junebugVisibleForUser: vi.fn(() => true),
}))
vi.mock("next-auth", () => ({
  getServerSession: vi.fn(),
}))
vi.mock("@/lib/auth/options", () => ({
  authOptions: {},
}))
vi.mock("@/lib/db", () => ({
  prisma: {
    junebugThread: {
      findUnique: vi.fn(),
    },
  },
}))

import { requireJunebugSession, requireOwnedThread } from "./thread-access"
import { junebugVisibleForUser } from "./feature-flag"
import { getServerSession } from "next-auth"
import { prisma } from "@/lib/db"

describe("requireJunebugSession", () => {
  beforeEach(() => {
    vi.clearAllMocks()
    ;(junebugVisibleForUser as any).mockReturnValue(true)
  })

  it("returns 404 when Junebug is not visible for this user (beta gate)", async () => {
    // Non-beta user — gate returns false regardless of whether the
    // session is valid. 404, no JSON body (no existence leak).
    ;(junebugVisibleForUser as any).mockReturnValue(false)
    ;(getServerSession as any).mockResolvedValue({
      user: { id: "user_abc", email: "non-beta@example.com" },
    })
    const r = await requireJunebugSession()
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.response.status).toBe(404)
      expect(r.response.body).toBeNull()
    }
  })

  it("returns 404 when the global flag is off (junebugVisibleForUser returns false)", async () => {
    ;(junebugVisibleForUser as any).mockReturnValue(false)
    ;(getServerSession as any).mockResolvedValue(null)
    const r = await requireJunebugSession()
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.response.status).toBe(404)
  })

  it("passes the session email to the visibility gate", async () => {
    ;(getServerSession as any).mockResolvedValue({
      user: { id: "user_abc", email: "beta@firm.com" },
    })
    await requireJunebugSession()
    expect(junebugVisibleForUser).toHaveBeenCalledWith("beta@firm.com")
  })

  it("returns 401 when flag is on for everyone but there's no session at all", async () => {
    // No beta gate → visibility returns true for anyone (including
    // missing email). But the route still needs a session.
    ;(junebugVisibleForUser as any).mockReturnValue(true)
    ;(getServerSession as any).mockResolvedValue(null)
    const r = await requireJunebugSession()
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.response.status).toBe(401)
  })

  it("returns 401 when session exists but session.user is null", async () => {
    ;(getServerSession as any).mockResolvedValue({ user: null })
    const r = await requireJunebugSession()
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.response.status).toBe(401)
  })

  it("returns { ok: true, userId } on a valid session", async () => {
    ;(getServerSession as any).mockResolvedValue({ user: { id: "user_abc" } })
    const r = await requireJunebugSession()
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.userId).toBe("user_abc")
  })
})

describe("requireOwnedThread", () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it("returns 404 when the thread doesn't exist (no existence leak)", async () => {
    ;(prisma.junebugThread.findUnique as any).mockResolvedValue(null)
    const r = await requireOwnedThread("t_missing", "user_1")
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.response.status).toBe(404)
      expect(r.response.body).toBeNull()
    }
  })

  it("returns 404 (NOT 403) when thread belongs to another user", async () => {
    // Critical: 403 would leak "this thread exists, you just can't touch it"
    // which lets a client enumerate other users' thread IDs.
    ;(prisma.junebugThread.findUnique as any).mockResolvedValue({
      id: "t_other",
      userId: "user_OTHER",
      caseId: null,
      titleAutoGenerated: false,
    })
    const r = await requireOwnedThread("t_other", "user_1")
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.response.status).toBe(404)
  })

  it("returns { ok: true, thread } when the user owns the thread", async () => {
    const row = {
      id: "t_owned",
      userId: "user_1",
      caseId: "case_42",
      titleAutoGenerated: true,
    }
    ;(prisma.junebugThread.findUnique as any).mockResolvedValue(row)
    const r = await requireOwnedThread("t_owned", "user_1")
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.thread).toEqual(row)
  })

  it("only selects the columns needed for ownership + audit (no content leak)", async () => {
    ;(prisma.junebugThread.findUnique as any).mockResolvedValue({
      id: "t", userId: "u", caseId: null, titleAutoGenerated: true,
    })
    await requireOwnedThread("t", "u")
    // The select shape must NOT include content / summary / title.
    // Those fields are read separately by callers that need them,
    // keeping this fast gate lean and avoiding accidental leaks.
    const call = (prisma.junebugThread.findUnique as any).mock.calls[0][0]
    expect(call.select).toEqual({
      id: true,
      userId: true,
      caseId: true,
      titleAutoGenerated: true,
    })
  })

  it("queries by the exact threadId param (not interpolated)", async () => {
    ;(prisma.junebugThread.findUnique as any).mockResolvedValue(null)
    await requireOwnedThread("t_injection'--", "user_1")
    const call = (prisma.junebugThread.findUnique as any).mock.calls[0][0]
    // Prisma parameterizes via `where: { id: ... }`, so even a
    // SQL-injection-looking string is passed as a bound param. The
    // test pins that behavior — if someone ever switches this to raw
    // SQL, the test would need to be reconsidered.
    expect(call.where).toEqual({ id: "t_injection'--" })
  })
})
