/**
 * Junebug thread title generation (spec §6.5.2).
 *
 * Called fire-and-forget from the messages route after the first user
 * message lands. If the call succeeds, PATCH the thread's title (keep
 * titleAutoGenerated = true so future regens can still run). If it
 * fails, the placeholder ("New conversation") stays.
 *
 * Falls back to a truncated first-message excerpt on Haiku failure so
 * the thread list never sits on "New conversation" forever — even in
 * the degraded case we surface something sensible. Spec §13 blesses
 * this permanent fallback.
 *
 * Bundle: Anthropic SDK only (already externalized). No tokenizer
 * dance at this layer — the caller pre-tokenizes the first message
 * (passes the raw content; we tokenize here, detokenize the title
 * back before storing since the practitioner-facing title must never
 * show [NAME-A1B2C3]).
 */

import Anthropic from "@anthropic-ai/sdk"
import { tokenizeText, detokenizeText } from "@/lib/ai/tokenizer"
import { prisma } from "@/lib/db"

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || "" })

// Matches the Haiku slug already used in humanizer.ts. If the codebase
// bumps Haiku versions elsewhere, update here too.
const TITLE_MODEL = "claude-haiku-4-5-20241022"
const TITLE_MAX_WORDS = 7
const TITLE_MAX_CHARS = 80
const FALLBACK_CHAR_LIMIT = 60

const SYSTEM_PROMPT = `Generate a 3-7 word title summarizing this question or request. Return only the title text. No quotes. No trailing punctuation. No leading "Title:". Title case.`

/**
 * Best-effort title generation. Never throws — returns a fallback
 * excerpt if Haiku or the DB update fails.
 *
 * Two-phase write (spec §13 "permanent fallback"): we immediately
 * patch the thread with the heuristic fallback so the sidebar shows
 * something sensible before Haiku returns. Haiku's smarter title
 * then overwrites it on success. Without the pre-patch, sidebars
 * display "New conversation" for 1–2 seconds on first message, and
 * longer if Haiku is slow or has a brief outage.
 */
export async function generateAndSaveThreadTitle(
  threadId: string,
  firstUserMessage: string,
  knownNames: string[] = []
): Promise<string | null> {
  const fallback = buildFallback(firstUserMessage)

  // Phase 1 — synchronous pre-fill with the heuristic fallback.
  // Guarantees the sidebar never sits on "New conversation" while
  // Haiku runs. Uses updateMany so a concurrent user rename isn't
  // clobbered (titleAutoGenerated=false excludes the thread).
  await safelyPatchTitle(threadId, fallback)

  if (!process.env.ANTHROPIC_API_KEY) {
    return fallback
  }

  try {
    const { tokenizedText, tokenMap } = tokenizeText(firstUserMessage, knownNames)

    const resp = await anthropic.messages.create({
      model: TITLE_MODEL,
      max_tokens: 60,
      temperature: 0.4,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: tokenizedText }],
    })

    const rawTitle = resp.content
      .filter((b) => b.type === "text")
      .map((b) => ("text" in b ? b.text : ""))
      .join("")
      .trim()

    const cleaned = cleanTitle(rawTitle)
    const detokenized = Object.keys(tokenMap).length > 0
      ? detokenizeText(cleaned, tokenMap)
      : cleaned

    const finalTitle = detokenized && detokenized.length > 0 ? detokenized : fallback

    // Phase 2 — upgrade to Haiku's title when it differs from the
    // pre-patched fallback. Skipping the redundant write when they
    // match saves a DB round-trip and, more importantly, preserves
    // the `updatedAt` from phase 1.
    if (finalTitle !== fallback) {
      await safelyPatchTitle(threadId, finalTitle)
    }
    return finalTitle
  } catch {
    // Haiku failure — fallback is already in place from phase 1.
    return fallback
  }
}

/**
 * Word-bounded truncation of the first message, used when Haiku is
 * unavailable. Per spec §13, this is a permanent fallback.
 *
 * Exported for unit tests; not part of the module's public API for
 * other callers.
 */
export function buildFallback(message: string): string {
  const trimmed = message.trim().replace(/\s+/g, " ")
  if (trimmed.length <= FALLBACK_CHAR_LIMIT) return trimmed
  const cut = trimmed.slice(0, FALLBACK_CHAR_LIMIT)
  // Truncate at a word boundary if possible
  const lastSpace = cut.lastIndexOf(" ")
  return (lastSpace > 20 ? cut.slice(0, lastSpace) : cut).trim() + "…"
}

/**
 * Post-process Haiku's title output: strip wrapping quotes, drop
 * leading "Title:" prefixes, trim trailing punctuation, and cap word
 * count + length. Exported for unit tests.
 */
export function cleanTitle(raw: string): string {
  let t = raw.trim()
  // Strip surrounding quotes. Includes ASCII " ' plus the smart-quote
  // variants Haiku frequently emits (left/right double \u201c\u201d and
  // left/right single \u2018\u2019). The previous regex was written
  // with what looked like smart quotes in the source but were actually
  // ASCII " characters — a real bug caught by the unit tests.
  t = t.replace(/^[\"'\u201c\u201d\u2018\u2019]+/, "").replace(/[\"'\u201c\u201d\u2018\u2019]+$/, "")
  // Strip leading "Title:" / "TITLE -"
  t = t.replace(/^(?:title|conversation|subject)\s*[:\-\u2013]\s*/i, "")
  // Strip trailing period / exclamation / question mark clusters
  t = t.replace(/[.!?]+$/, "")
  // Hard cap on length + word count
  const words = t.split(/\s+/).filter(Boolean)
  if (words.length > TITLE_MAX_WORDS) t = words.slice(0, TITLE_MAX_WORDS).join(" ")
  if (t.length > TITLE_MAX_CHARS) t = t.slice(0, TITLE_MAX_CHARS).trim() + "…"
  return t
}

async function safelyPatchTitle(threadId: string, title: string): Promise<void> {
  try {
    // updateMany with the titleAutoGenerated=true filter is the only
    // way to conditionally skip the write when the user has already
    // renamed — `update` throws on zero matches, which would bubble
    // up as a noisy error, and unconditional update would clobber
    // the rename. A race between a user rename and this patch picks
    // the rename as the winner, which matches user expectation.
    await prisma.junebugThread.updateMany({
      where: {
        id: threadId,
        titleAutoGenerated: true,
      },
      data: {
        title,
        titleAutoGenerated: true,
      },
    })
  } catch {
    // Non-fatal. The thread keeps its placeholder.
  }
}

/**
 * Tighter gate used by the caller to decide whether to fire title gen.
 * Matches the "first USER message AND title is still auto-generated"
 * rule from §6.5.2.
 */
export function shouldGenerateTitle(opts: {
  titleAutoGenerated: boolean
  priorUserMessageCount: number
}): boolean {
  return opts.titleAutoGenerated && opts.priorUserMessageCount === 0
}
