import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { prisma } from "@/lib/db"
import { decryptField } from "@/lib/encryption"
import { requireJunebugSession } from "@/lib/junebug/thread-access"
import { createAuditLog, AUDIT_ACTIONS } from "@/lib/ai/audit"

/**
 * /api/junebug/threads — GET list, POST create (spec §6.1, §6.2).
 *
 * GET filters: archived, caseId, pinnedOnly, search (Postgres FTS),
 * cursor (opaque ISO timestamp + id), limit (default 30, max 100).
 *
 * POST creates an empty thread immediately so the UI can navigate to it.
 * Empty threads older than 24h get cleaned up by /api/cron/junebug/cleanup
 * (PR 5).
 */

// ============================================================
// GET — list
// ============================================================

const DEFAULT_LIMIT = 30
const MAX_LIMIT = 100
const LAST_MESSAGE_PREVIEW_CHARS = 120

interface ListThreadResult {
  id: string
  title: string
  titleAutoGenerated: boolean
  caseId: string | null
  caseNumber: string | null
  clientName: string | null
  pinned: boolean
  archived: boolean
  lastMessageAt: string
  createdAt: string
  messageCount: number
  lastMessagePreview: string
  lastMessageRole: "USER" | "ASSISTANT" | "SYSTEM" | null
}

export async function GET(request: NextRequest) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const sp = request.nextUrl.searchParams
  const archived = sp.get("archived") === "true"
  const pinnedOnly = sp.get("pinnedOnly") === "true"
  const caseId = sp.get("caseId") || undefined
  const search = (sp.get("search") || "").trim()
  const cursor = sp.get("cursor") || undefined
  const limit = clampLimit(sp.get("limit"))

  // Build the WHERE common to search and non-search paths
  const baseWhere: any = {
    userId: auth.userId,
    archived,
  }
  if (pinnedOnly) baseWhere.pinned = true
  if (caseId) baseWhere.caseId = caseId

  // Cursor pagination: the client sends back `lastMessageAt|id` from the last
  // row of the previous page. We use a compound comparison so pages are
  // stable even when many rows share a lastMessageAt.
  const cursorFilter = decodeCursor(cursor)
  if (cursorFilter) {
    baseWhere.AND = [
      ...(baseWhere.AND ?? []),
      {
        OR: [
          { lastMessageAt: { lt: cursorFilter.lastMessageAt } },
          {
            lastMessageAt: cursorFilter.lastMessageAt,
            id: { lt: cursorFilter.id },
          },
        ],
      },
    ]
  }

  let threadIdsOrdered: string[]

  if (search) {
    // Postgres FTS across the user's messages. Find matching threads, rank
    // by summed ts_rank_cd across their messages, break ties by recency.
    const rows = await prisma.$queryRawUnsafe<
      Array<{ threadId: string; rank: number; lastMessageAt: Date }>
    >(
      `
      SELECT t.id AS "threadId", SUM(ts_rank_cd(to_tsvector('english', m.content),
             plainto_tsquery('english', $1::text), 32)) AS rank,
             MAX(t."lastMessageAt") AS "lastMessageAt"
      FROM junebug_messages m
      JOIN junebug_threads t ON t.id = m."threadId"
      WHERE t."userId" = $2
        AND t.archived = $3
        ${pinnedOnly ? 'AND t.pinned = true' : ''}
        ${caseId ? 'AND t."caseId" = $4' : ''}
        AND to_tsvector('english', m.content) @@ plainto_tsquery('english', $1::text)
      GROUP BY t.id
      ORDER BY rank DESC, "lastMessageAt" DESC
      LIMIT $${caseId ? 5 : 4}
      `,
      search,
      auth.userId,
      archived,
      ...(caseId ? [caseId, limit + 1] : [limit + 1])
    )
    threadIdsOrdered = rows.map((r) => r.threadId)
  } else {
    // Standard list — pinned first (within the archived flag), then by
    // lastMessageAt desc. Fetch limit + 1 so we can tell if there's a next page.
    const rows = await prisma.junebugThread.findMany({
      where: baseWhere,
      orderBy: [
        { pinned: "desc" },
        { lastMessageAt: "desc" },
        { id: "desc" },
      ],
      take: limit + 1,
      select: { id: true },
    })
    threadIdsOrdered = rows.map((r) => r.id)
  }

  const hasMore = threadIdsOrdered.length > limit
  if (hasMore) threadIdsOrdered = threadIdsOrdered.slice(0, limit)

  if (threadIdsOrdered.length === 0) {
    return NextResponse.json({ threads: [], nextCursor: null })
  }

  // Hydrate metadata + last-message preview in one pass
  const threads = await prisma.junebugThread.findMany({
    where: { id: { in: threadIdsOrdered } },
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
      _count: { select: { messages: true } },
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { role: true, content: true },
      },
    },
  })

  // Restore the ordering from our ranked/sorted id list
  const byId = new Map(threads.map((t) => [t.id, t]))
  const hydrated: ListThreadResult[] = threadIdsOrdered.flatMap((id) => {
    const t = byId.get(id)
    if (!t) return []
    const last = t.messages[0]
    let clientName: string | null = null
    if (t.case?.clientName) {
      try {
        clientName = decryptField(t.case.clientName)
      } catch {
        clientName = null
      }
    }
    return [{
      id: t.id,
      title: t.title,
      titleAutoGenerated: t.titleAutoGenerated,
      caseId: t.caseId,
      caseNumber: t.case?.tabsNumber ?? null,
      clientName,
      pinned: t.pinned,
      archived: t.archived,
      lastMessageAt: t.lastMessageAt.toISOString(),
      createdAt: t.createdAt.toISOString(),
      messageCount: t._count.messages,
      lastMessagePreview: last?.content
        ? last.content.slice(0, LAST_MESSAGE_PREVIEW_CHARS)
        : "",
      lastMessageRole: (last?.role as any) ?? null,
    }]
  })

  const lastThread = hydrated[hydrated.length - 1]
  const nextCursor = hasMore && lastThread
    ? encodeCursor({ lastMessageAt: new Date(lastThread.lastMessageAt), id: lastThread.id })
    : null

  return NextResponse.json({ threads: hydrated, nextCursor })
}

// ============================================================
// POST — create
// ============================================================

const createSchema = z.object({
  caseId: z.string().cuid().optional().nullable(),
})

export async function POST(request: NextRequest) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  let body: z.infer<typeof createSchema>
  try {
    body = createSchema.parse(await request.json().catch(() => ({})))
  } catch (err: any) {
    return NextResponse.json(
      { error: "Invalid body", detail: err?.message },
      { status: 400 }
    )
  }

  // Validate case access if caseId provided — we don't need the full
  // canAccessCase gate here since threads are already per-user, but we
  // should make sure the case exists and isn't someone else's closed record.
  if (body.caseId) {
    const caseExists = await prisma.case.findUnique({
      where: { id: body.caseId },
      select: { id: true },
    })
    if (!caseExists) {
      return NextResponse.json({ error: "Case not found" }, { status: 404 })
    }
  }

  const thread = await prisma.junebugThread.create({
    data: {
      userId: auth.userId,
      caseId: body.caseId ?? null,
      title: "New conversation",
      titleAutoGenerated: true,
    },
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
    },
  })

  // Audit — fire-and-forget. Never block the create path.
  createAuditLog({
    practitionerId: auth.userId,
    caseId: body.caseId ?? undefined,
    action: AUDIT_ACTIONS.JUNEBUG_THREAD_CREATED,
    metadata: { threadId: thread.id },
  }).catch(() => {})

  let clientName: string | null = null
  if (thread.case?.clientName) {
    try {
      clientName = decryptField(thread.case.clientName)
    } catch {
      clientName = null
    }
  }

  return NextResponse.json(
    {
      thread: {
        id: thread.id,
        title: thread.title,
        titleAutoGenerated: thread.titleAutoGenerated,
        caseId: thread.caseId,
        caseNumber: thread.case?.tabsNumber ?? null,
        clientName,
        pinned: thread.pinned,
        archived: thread.archived,
        lastMessageAt: thread.lastMessageAt.toISOString(),
        createdAt: thread.createdAt.toISOString(),
        messageCount: 0,
        lastMessagePreview: "",
        lastMessageRole: null,
      },
    },
    { status: 201 }
  )
}

// ============================================================
// Helpers
// ============================================================

function clampLimit(raw: string | null): number {
  if (!raw) return DEFAULT_LIMIT
  const n = Number.parseInt(raw, 10)
  if (!Number.isFinite(n) || n < 1) return DEFAULT_LIMIT
  return Math.min(n, MAX_LIMIT)
}

/** Encode cursor as `ISO|id` base64 so it's opaque to the client. */
function encodeCursor(c: { lastMessageAt: Date; id: string }): string {
  return Buffer.from(`${c.lastMessageAt.toISOString()}|${c.id}`).toString("base64url")
}

function decodeCursor(raw: string | undefined): { lastMessageAt: Date; id: string } | null {
  if (!raw) return null
  try {
    const decoded = Buffer.from(raw, "base64url").toString("utf-8")
    const [isoStr, id] = decoded.split("|")
    if (!isoStr || !id) return null
    const d = new Date(isoStr)
    if (Number.isNaN(d.getTime())) return null
    return { lastMessageAt: d, id }
  } catch {
    return null
  }
}
