import { FormSchema } from "../types"

export const FORM_433A: FormSchema = {
  formNumber: "433-A",
  formTitle: "Collection Information Statement for Wage Earners and Self-Employed Individuals",
  revisionDate: "April 2023",
  ombNumber: "1545-0074",
  totalSections: 6,
  estimatedMinutes: 45,
  resolutionMetadata: {
    resolutionPaths: ["ia", "cnc", "cdp", "penalty", "innocent_spouse"],
    requirementLevel: { ia: "required", cnc: "required", cdp: "recommended", oic: "recommended" },
    dependsOn: ["2848"],
    requiredBy: ["656"],
    dataSources: [],
    dataTargets: ["433-A-OIC", "656", "911", "12153"],
  },
  sections: [
    // ── Section 1: Personal & Household Information ──────────────────────
    {
      id: "personal",
      title: "Personal & Household Information",
      description: "Taxpayer identification, contact information, and household details",
      order: 1,
      fields: [
        {
          id: "taxpayer_name",
          label: "Full Name",
          type: "text",
          required: true,
          irsReference: "Line 1a",
          validation: [
            { type: "required", message: "Taxpayer name is required" },
            { type: "max_length", value: 100, message: "Name too long" },
          ],
        },
        {
          id: "ssn",
          label: "Social Security Number",
          type: "ssn",
          required: true,
          irsReference: "Line 1b",
          validation: [
            { type: "required", message: "SSN is required" },
            { type: "pattern", value: "^\\d{3}-?\\d{2}-?\\d{4}$", message: "Invalid SSN format" },
          ],
        },
        {
          id: "dob",
          label: "Date of Birth",
          type: "date",
          required: true,
          irsReference: "Line 1c",
        },
        {
          id: "address_street",
          label: "Street Address",
          type: "text",
          required: true,
          irsReference: "Line 2a",
        },
        {
          id: "address_city",
          label: "City",
          type: "text",
          required: true,
        },
        {
          id: "address_state",
          label: "State",
          type: "single_select",
          required: true,
          options: [
            { value: "AL", label: "Alabama" },
            { value: "AK", label: "Alaska" },
            { value: "AZ", label: "Arizona" },
            { value: "AR", label: "Arkansas" },
            { value: "CA", label: "California" },
            { value: "CO", label: "Colorado" },
            { value: "CT", label: "Connecticut" },
            { value: "DE", label: "Delaware" },
            { value: "DC", label: "District of Columbia" },
            { value: "FL", label: "Florida" },
            { value: "GA", label: "Georgia" },
            { value: "HI", label: "Hawaii" },
            { value: "ID", label: "Idaho" },
            { value: "IL", label: "Illinois" },
            { value: "IN", label: "Indiana" },
            { value: "IA", label: "Iowa" },
            { value: "KS", label: "Kansas" },
            { value: "KY", label: "Kentucky" },
            { value: "LA", label: "Louisiana" },
            { value: "ME", label: "Maine" },
            { value: "MD", label: "Maryland" },
            { value: "MA", label: "Massachusetts" },
            { value: "MI", label: "Michigan" },
            { value: "MN", label: "Minnesota" },
            { value: "MS", label: "Mississippi" },
            { value: "MO", label: "Missouri" },
            { value: "MT", label: "Montana" },
            { value: "NE", label: "Nebraska" },
            { value: "NV", label: "Nevada" },
            { value: "NH", label: "New Hampshire" },
            { value: "NJ", label: "New Jersey" },
            { value: "NM", label: "New Mexico" },
            { value: "NY", label: "New York" },
            { value: "NC", label: "North Carolina" },
            { value: "ND", label: "North Dakota" },
            { value: "OH", label: "Ohio" },
            { value: "OK", label: "Oklahoma" },
            { value: "OR", label: "Oregon" },
            { value: "PA", label: "Pennsylvania" },
            { value: "RI", label: "Rhode Island" },
            { value: "SC", label: "South Carolina" },
            { value: "SD", label: "South Dakota" },
            { value: "TN", label: "Tennessee" },
            { value: "TX", label: "Texas" },
            { value: "UT", label: "Utah" },
            { value: "VT", label: "Vermont" },
            { value: "VA", label: "Virginia" },
            { value: "WA", label: "Washington" },
            { value: "WV", label: "West Virginia" },
            { value: "WI", label: "Wisconsin" },
            { value: "WY", label: "Wyoming" },
          ],
        },
        {
          id: "address_zip",
          label: "ZIP Code",
          type: "text",
          required: true,
          validation: [
            { type: "pattern", value: "^\\d{5}(-\\d{4})?$", message: "Invalid ZIP" },
          ],
        },
        {
          id: "county",
          label: "County",
          type: "text",
          helpText: "Used for IRS Allowable Living Expense standards lookup",
        },
        {
          id: "marital_status",
          label: "Marital Status",
          type: "single_select",
          required: true,
          irsReference: "Line 4",
          options: [
            { value: "single", label: "Single" },
            { value: "married", label: "Married" },
            { value: "separated", label: "Separated" },
            { value: "divorced", label: "Divorced" },
            { value: "widowed", label: "Widowed" },
          ],
        },
        {
          id: "home_phone",
          label: "Home Phone",
          type: "phone",
          irsReference: "Line 3a",
        },
        {
          id: "cell_phone",
          label: "Cell Phone",
          type: "phone",
          irsReference: "Line 3b",
        },
        // Spouse info (conditional on married)
        {
          id: "spouse_name",
          label: "Spouse Full Name",
          type: "text",
          irsReference: "Line 5a",
          conditionals: [
            { field: "marital_status", operator: "equals", value: "married", action: "show" },
          ],
        },
        {
          id: "spouse_ssn",
          label: "Spouse SSN",
          type: "ssn",
          irsReference: "Line 5b",
          conditionals: [
            { field: "marital_status", operator: "equals", value: "married", action: "show" },
          ],
        },
        {
          id: "spouse_dob",
          label: "Spouse Date of Birth",
          type: "date",
          irsReference: "Line 5c",
          conditionals: [
            { field: "marital_status", operator: "equals", value: "married", action: "show" },
          ],
        },
        // Dependents repeating group
        {
          id: "dependents",
          label: "Dependents",
          type: "repeating_group",
          irsReference: "Line 6",
          minGroups: 0,
          maxGroups: 10,
          groupFields: [
            { id: "dep_name", label: "Name", type: "text", required: true },
            { id: "dep_dob", label: "Date of Birth", type: "date", required: true },
            {
              id: "dep_relationship",
              label: "Relationship",
              type: "single_select",
              options: [
                { value: "child", label: "Child" },
                { value: "parent", label: "Parent" },
                { value: "other", label: "Other" },
              ],
            },
            { id: "dep_lives_with", label: "Lives with you?", type: "yes_no" },
            { id: "dep_contributes", label: "Contributes to support?", type: "yes_no" },
          ],
        },
      ],
    },

    // ── Section 2: Employment & Income Sources ──────────────────────────
    {
      id: "employment",
      title: "Employment & Income Sources",
      description: "Current employment, self-employment, and other income sources",
      order: 2,
      fields: [
        {
          id: "employment_type",
          label: "Employment Type",
          type: "single_select",
          required: true,
          irsReference: "Line 7",
          options: [
            { value: "wage_earner", label: "Wage Earner (W-2)" },
            { value: "self_employed", label: "Self-Employed" },
            { value: "both", label: "Both" },
            { value: "neither", label: "Neither (Retired/Unemployed)" },
          ],
        },
        // Employers repeating group
        {
          id: "employers",
          label: "Employers",
          type: "repeating_group",
          irsReference: "Lines 8-12",
          minGroups: 0,
          maxGroups: 5,
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "self_employed", action: "show" },
          ],
          groupFields: [
            { id: "emp_name", label: "Employer Name", type: "text", required: true },
            { id: "emp_address", label: "Employer Address", type: "text" },
            { id: "emp_phone", label: "Employer Phone", type: "phone" },
            { id: "emp_ein", label: "Employer EIN", type: "ein" },
            { id: "emp_hire_date", label: "Hire Date", type: "date" },
            { id: "emp_gross_monthly", label: "Gross Monthly Pay", type: "currency", required: true },
            { id: "emp_net_monthly", label: "Net Monthly Pay", type: "currency" },
            {
              id: "emp_pay_frequency",
              label: "Pay Frequency",
              type: "single_select",
              options: [
                { value: "weekly", label: "Weekly" },
                { value: "biweekly", label: "Bi-Weekly" },
                { value: "semimonthly", label: "Semi-Monthly" },
                { value: "monthly", label: "Monthly" },
              ],
            },
          ],
        },
        // Self-employment fields
        {
          id: "business_name",
          label: "Business Name",
          type: "text",
          irsReference: "Line 13",
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
        {
          id: "business_ein",
          label: "Business EIN",
          type: "ein",
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
        {
          id: "business_type",
          label: "Type of Business",
          type: "text",
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
        {
          id: "business_gross_monthly",
          label: "Average Monthly Gross Receipts",
          type: "currency",
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
        {
          id: "business_expenses_monthly",
          label: "Average Monthly Business Expenses",
          type: "currency",
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
        {
          id: "business_net_monthly",
          label: "Net Monthly Business Income",
          type: "computed",
          computeFormula: "business_gross_monthly - business_expenses_monthly",
          dependsOn: ["business_gross_monthly", "business_expenses_monthly"],
          conditionals: [
            { field: "employment_type", operator: "not_equals", value: "wage_earner", action: "show" },
          ],
        },
      ],
    },

    // ── Section 3: Personal Assets & Liabilities ────────────────────────
    {
      id: "assets",
      title: "Personal Assets & Liabilities",
      description: "Bank accounts, vehicles, real property, retirement accounts, and other assets",
      order: 3,
      fields: [
        // Bank accounts
        {
          id: "bank_accounts",
          label: "Bank Accounts",
          type: "repeating_group",
          irsReference: "Lines 14a-14c",
          minGroups: 0,
          maxGroups: 10,
          groupFields: [
            { id: "bank_name", label: "Bank Name", type: "text", required: true },
            {
              id: "bank_account_type",
              label: "Account Type",
              type: "single_select",
              options: [
                { value: "checking", label: "Checking" },
                { value: "savings", label: "Savings" },
                { value: "money_market", label: "Money Market" },
                { value: "cd", label: "Certificate of Deposit" },
              ],
            },
            { id: "bank_balance", label: "Current Balance", type: "currency", required: true },
          ],
        },
        {
          id: "total_bank_balances",
          label: "Total Bank Balances",
          type: "computed",
          computeFormula: "SUM(bank_accounts.bank_balance)",
          irsReference: "Line 14 Total",
        },
        // Investments
        {
          id: "investments",
          label: "Investment Accounts",
          type: "repeating_group",
          irsReference: "Line 15",
          minGroups: 0,
          maxGroups: 10,
          groupFields: [
            { id: "inv_institution", label: "Institution", type: "text", required: true },
            {
              id: "inv_type",
              label: "Account Type",
              type: "single_select",
              options: [
                { value: "brokerage", label: "Brokerage" },
                { value: "mutual_fund", label: "Mutual Fund" },
                { value: "stocks", label: "Stocks/Bonds" },
                { value: "other", label: "Other" },
              ],
            },
            { id: "inv_balance", label: "Current Value", type: "currency", required: true },
            { id: "inv_loan", label: "Outstanding Loan", type: "currency", defaultValue: 0 },
            {
              id: "inv_equity",
              label: "Net Equity",
              type: "computed",
              computeFormula: "inv_balance - inv_loan",
            },
          ],
        },
        // Real property
        {
          id: "real_property",
          label: "Real Property",
          type: "repeating_group",
          irsReference: "Line 16",
          minGroups: 0,
          maxGroups: 5,
          groupFields: [
            {
              id: "prop_description",
              label: "Description",
              type: "text",
              required: true,
              placeholder: "e.g., Primary residence, rental duplex",
            },
            { id: "prop_address", label: "Property Address", type: "text" },
            { id: "prop_fmv", label: "Fair Market Value", type: "currency", required: true },
            { id: "prop_loan", label: "Loan Balance", type: "currency", defaultValue: 0 },
            {
              id: "prop_equity",
              label: "Equity (FMV - Loan)",
              type: "computed",
              computeFormula: "prop_fmv - prop_loan",
            },
            { id: "prop_monthly_payment", label: "Monthly Payment", type: "currency" },
            { id: "prop_lender", label: "Lender Name", type: "text" },
          ],
        },
        // Vehicles
        {
          id: "vehicles",
          label: "Vehicles",
          type: "repeating_group",
          irsReference: "Line 18",
          minGroups: 0,
          maxGroups: 5,
          groupFields: [
            { id: "veh_year", label: "Year", type: "text", required: true },
            { id: "veh_make", label: "Make", type: "text", required: true },
            { id: "veh_model", label: "Model", type: "text", required: true },
            { id: "veh_mileage", label: "Current Mileage", type: "text" },
            { id: "veh_fmv", label: "Fair Market Value", type: "currency", required: true },
            { id: "veh_loan", label: "Loan Balance", type: "currency", defaultValue: 0 },
            {
              id: "veh_equity",
              label: "Equity",
              type: "computed",
              computeFormula: "veh_fmv - veh_loan",
            },
            { id: "veh_monthly_payment", label: "Monthly Payment", type: "currency" },
            { id: "veh_lender", label: "Lender", type: "text" },
          ],
        },
        // Retirement
        {
          id: "retirement_accounts",
          label: "Retirement Accounts",
          type: "repeating_group",
          irsReference: "Line 17",
          minGroups: 0,
          maxGroups: 5,
          groupFields: [
            { id: "ret_institution", label: "Institution", type: "text", required: true },
            {
              id: "ret_type",
              label: "Account Type",
              type: "single_select",
              options: [
                { value: "401k", label: "401(k)" },
                { value: "ira", label: "Traditional IRA" },
                { value: "roth", label: "Roth IRA" },
                { value: "pension", label: "Pension" },
                { value: "other", label: "Other" },
              ],
            },
            { id: "ret_balance", label: "Current Value", type: "currency", required: true },
            { id: "ret_loan", label: "Outstanding Loan", type: "currency", defaultValue: 0 },
          ],
        },
        // Other assets
        {
          id: "life_insurance_csv",
          label: "Whole Life Insurance Cash Surrender Value",
          type: "currency",
          irsReference: "Line 19",
        },
        {
          id: "other_assets",
          label: "Other Assets",
          type: "repeating_group",
          irsReference: "Line 20",
          minGroups: 0,
          maxGroups: 10,
          groupFields: [
            { id: "other_description", label: "Description", type: "text", required: true },
            { id: "other_fmv", label: "Fair Market Value", type: "currency", required: true },
            { id: "other_loan", label: "Loan/Encumbrance", type: "currency", defaultValue: 0 },
          ],
        },
        // Safe deposit boxes
        {
          id: "has_safe_deposit",
          label: "Do you have a safe deposit box?",
          type: "yes_no",
          irsReference: "Line 21",
        },
        {
          id: "safe_deposit_location",
          label: "Safe deposit box location",
          type: "text",
          conditionals: [
            { field: "has_safe_deposit", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "safe_deposit_contents",
          label: "Contents",
          type: "textarea",
          conditionals: [
            { field: "has_safe_deposit", operator: "equals", value: true, action: "show" },
          ],
        },
      ],
    },

    // ── Section 4: Monthly Income ───────────────────────────────────────
    {
      id: "monthly_income",
      title: "Monthly Income",
      description: "All sources of monthly household income",
      order: 4,
      fields: [
        {
          id: "income_wages",
          label: "Wages (from employment section)",
          type: "computed",
          computeFormula: "SUM(employers.emp_gross_monthly)",
          irsReference: "Line 45",
          helpText: "Computed from employment section",
        },
        {
          id: "income_ss",
          label: "Social Security",
          type: "currency",
          irsReference: "Line 46",
          defaultValue: 0,
        },
        {
          id: "income_pension",
          label: "Pension/Annuity",
          type: "currency",
          irsReference: "Line 47",
          defaultValue: 0,
        },
        {
          id: "income_self_employment",
          label: "Net Self-Employment Income",
          type: "computed",
          computeFormula: "business_net_monthly",
          irsReference: "Line 48",
        },
        {
          id: "income_rental",
          label: "Rental Income (net)",
          type: "currency",
          irsReference: "Line 49",
          defaultValue: 0,
        },
        {
          id: "income_interest_dividends",
          label: "Interest and Dividends",
          type: "currency",
          irsReference: "Line 50",
          defaultValue: 0,
        },
        {
          id: "income_distributions",
          label: "Distributions (IRA, 401k, etc.)",
          type: "currency",
          irsReference: "Line 51",
          defaultValue: 0,
        },
        {
          id: "income_child_support_alimony",
          label: "Child Support / Alimony Received",
          type: "currency",
          irsReference: "Line 52",
          defaultValue: 0,
        },
        {
          id: "income_other",
          label: "Other Income",
          type: "currency",
          irsReference: "Line 53",
          defaultValue: 0,
        },
        {
          id: "income_other_description",
          label: "Other Income Description",
          type: "text",
          conditionals: [
            { field: "income_other", operator: "greater_than", value: 0, action: "show" },
          ],
        },
        {
          id: "total_monthly_income",
          label: "Total Monthly Income",
          type: "computed",
          computeFormula: "income_wages + income_ss + income_pension + income_self_employment + income_rental + income_interest_dividends + income_distributions + income_child_support_alimony + income_other",
          irsReference: "Line 54",
        },
      ],
    },

    // ── Section 5: Monthly Expenses ─────────────────────────────────────
    {
      id: "monthly_expenses",
      title: "Monthly Expenses",
      description: "Allowable monthly living expenses per IRS Collection Financial Standards",
      order: 5,
      fields: [
        {
          id: "expense_food_clothing",
          label: "Food, Clothing & Miscellaneous",
          type: "currency",
          required: true,
          irsReference: "Line 55",
          helpText: "IRS National Standard applies. Your county standard will be suggested.",
        },
        {
          id: "expense_housing",
          label: "Housing and Utilities",
          type: "currency",
          required: true,
          irsReference: "Line 56",
          helpText: "IRS Local Standard for your county. Includes rent/mortgage, property tax, insurance, utilities.",
        },
        {
          id: "expense_vehicle_ownership",
          label: "Vehicle Ownership Costs",
          type: "currency",
          irsReference: "Line 57",
          helpText: "IRS Local Standard. Lease or loan payment.",
          defaultValue: 0,
        },
        {
          id: "expense_vehicle_operating",
          label: "Vehicle Operating Costs",
          type: "currency",
          irsReference: "Line 58",
          helpText: "IRS Local Standard. Gas, insurance, maintenance.",
          defaultValue: 0,
        },
        {
          id: "expense_public_transit",
          label: "Public Transportation",
          type: "currency",
          irsReference: "Line 59",
          defaultValue: 0,
        },
        {
          id: "expense_health_insurance",
          label: "Health Insurance",
          type: "currency",
          irsReference: "Line 60",
          defaultValue: 0,
        },
        {
          id: "expense_medical",
          label: "Out-of-Pocket Medical/Dental",
          type: "currency",
          irsReference: "Line 61",
          helpText: "IRS standard: $75/person (under 65) or $153/person (65+)",
          defaultValue: 0,
        },
        {
          id: "expense_court_ordered",
          label: "Court-Ordered Payments",
          type: "currency",
          irsReference: "Line 62",
          helpText: "Child support, alimony, restitution",
          defaultValue: 0,
        },
        {
          id: "expense_child_care",
          label: "Child/Dependent Care",
          type: "currency",
          irsReference: "Line 63",
          defaultValue: 0,
        },
        {
          id: "expense_life_insurance",
          label: "Term Life Insurance",
          type: "currency",
          irsReference: "Line 64",
          defaultValue: 0,
        },
        {
          id: "expense_taxes",
          label: "Current Tax Payments (estimated/withholding)",
          type: "currency",
          irsReference: "Line 65",
          defaultValue: 0,
        },
        {
          id: "expense_secured_debts",
          label: "Secured Debt Payments (not listed above)",
          type: "currency",
          irsReference: "Line 66",
          defaultValue: 0,
        },
        {
          id: "expense_other",
          label: "Other Necessary Expenses",
          type: "currency",
          irsReference: "Line 67",
          defaultValue: 0,
        },
        {
          id: "expense_other_description",
          label: "Other Expenses Description",
          type: "text",
          conditionals: [
            { field: "expense_other", operator: "greater_than", value: 0, action: "show" },
          ],
        },
        {
          id: "total_monthly_expenses",
          label: "Total Monthly Expenses",
          type: "computed",
          computeFormula: "expense_food_clothing + expense_housing + expense_vehicle_ownership + expense_vehicle_operating + expense_public_transit + expense_health_insurance + expense_medical + expense_court_ordered + expense_child_care + expense_life_insurance + expense_taxes + expense_secured_debts + expense_other",
          irsReference: "Line 68",
        },
        {
          id: "remaining_monthly_income",
          label: "Net Remaining Monthly Income",
          type: "computed",
          computeFormula: "total_monthly_income - total_monthly_expenses",
          irsReference: "Line 69",
          helpText: "This is the amount available for IRS payment",
        },
      ],
    },

    // ── Section 6: Other Financial Information ──────────────────────────
    {
      id: "other_info",
      title: "Other Financial Information",
      description: "Additional questions about financial history and circumstances",
      order: 6,
      fields: [
        {
          id: "filed_bankruptcy",
          label: "Have you filed bankruptcy in the last 7 years?",
          type: "yes_no",
          irsReference: "Line 22",
        },
        {
          id: "bankruptcy_date",
          label: "Date Filed",
          type: "date",
          conditionals: [
            { field: "filed_bankruptcy", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "bankruptcy_dismissed",
          label: "Has it been dismissed or discharged?",
          type: "yes_no",
          conditionals: [
            { field: "filed_bankruptcy", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "involved_lawsuit",
          label: "Are you a party to any lawsuit?",
          type: "yes_no",
          irsReference: "Line 23",
        },
        {
          id: "lawsuit_details",
          label: "Lawsuit Details",
          type: "textarea",
          conditionals: [
            { field: "involved_lawsuit", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "transferred_assets",
          label: "Have you transferred any assets in the last 10 years?",
          type: "yes_no",
          irsReference: "Line 24",
          helpText: "Sold, gifted, or transferred assets for less than fair market value",
        },
        {
          id: "transfer_details",
          label: "Transfer Details",
          type: "textarea",
          conditionals: [
            { field: "transferred_assets", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "anticipated_income_change",
          label: "Do you expect any significant change in income?",
          type: "yes_no",
          irsReference: "Line 25",
        },
        {
          id: "income_change_details",
          label: "Expected Change Details",
          type: "textarea",
          conditionals: [
            { field: "anticipated_income_change", operator: "equals", value: true, action: "show" },
          ],
        },
        {
          id: "trust_interest",
          label: "Are you a beneficiary of a trust, estate, or profit-sharing plan?",
          type: "yes_no",
          irsReference: "Line 26",
        },
        {
          id: "trust_details",
          label: "Trust/Estate Details",
          type: "textarea",
          conditionals: [
            { field: "trust_interest", operator: "equals", value: true, action: "show" },
          ],
        },
      ],
    },
  ],
  crossFieldValidations: [
    {
      id: "income_total_check",
      description: "Total monthly income must equal sum of all income line items",
      fields: [
        "total_monthly_income",
        "income_wages",
        "income_ss",
        "income_pension",
        "income_self_employment",
        "income_rental",
        "income_interest_dividends",
        "income_distributions",
        "income_child_support_alimony",
        "income_other",
      ],
      rule: "total_monthly_income === income_wages + income_ss + income_pension + income_self_employment + income_rental + income_interest_dividends + income_distributions + income_child_support_alimony + income_other",
      errorMessage: "Total monthly income does not match the sum of income line items",
      severity: "error",
    },
    {
      id: "expense_total_check",
      description: "Total monthly expenses must equal sum of all expense line items",
      fields: ["total_monthly_expenses"],
      rule: "total_monthly_expenses === sum_of_expenses",
      errorMessage: "Total monthly expenses does not match the sum of expense line items",
      severity: "error",
    },
  ],
}
