import { describe, it, expect, beforeEach, afterEach, vi } from "vitest"
import { groupThreads, formatRelativeShort } from "./group-threads"
import type { JunebugThreadListItem } from "../types"

/**
 * Build a minimal thread fixture. lastMessageAt is the field the
 * grouper buckets on; pinned overrides bucket assignment.
 */
function thread(overrides: Partial<JunebugThreadListItem> & Pick<JunebugThreadListItem, "id" | "lastMessageAt">): JunebugThreadListItem {
  return {
    title: "test",
    titleAutoGenerated: true,
    caseId: null,
    caseNumber: null,
    clientName: null,
    pinned: false,
    archived: false,
    createdAt: overrides.lastMessageAt,
    messageCount: 0,
    lastMessagePreview: "",
    lastMessageRole: null,
    ...overrides,
  }
}

describe("groupThreads", () => {
  // Pin "now" to a deterministic moment so the relative buckets are
  // testable. 2026-04-15 14:00 local — pick a midweek mid-day so we
  // don't trip on DST or month boundaries.
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date("2026-04-15T14:00:00"))
  })
  afterEach(() => {
    vi.useRealTimers()
  })

  it("returns no groups for empty input", () => {
    expect(groupThreads([])).toEqual([])
  })

  it("buckets a thread from earlier today as Today", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-04-15T09:00:00" })
    const groups = groupThreads([t])
    expect(groups).toHaveLength(1)
    expect(groups[0].key).toBe("today")
    expect(groups[0].threads).toEqual([t])
  })

  it("buckets a thread from yesterday as Yesterday", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-04-14T18:00:00" })
    expect(groupThreads([t])[0].key).toBe("yesterday")
  })

  it("buckets a thread from 4 days ago as Previous 7 days", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-04-11T12:00:00" })
    expect(groupThreads([t])[0].key).toBe("prev7")
  })

  it("buckets a thread from 14 days ago as Previous 30 days", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-04-01T12:00:00" })
    expect(groupThreads([t])[0].key).toBe("prev30")
  })

  it("buckets a thread from 60 days ago as Older", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-02-14T12:00:00" })
    expect(groupThreads([t])[0].key).toBe("older")
  })

  it("hoists pinned threads regardless of recency", () => {
    const today = thread({ id: "1", lastMessageAt: "2026-04-15T09:00:00", pinned: false })
    const ancientButPinned = thread({ id: "2", lastMessageAt: "2025-01-01T00:00:00", pinned: true })
    const groups = groupThreads([today, ancientButPinned])
    // Pinned group always first when present
    expect(groups[0].key).toBe("pinned")
    expect(groups[0].threads.map((t) => t.id)).toEqual(["2"])
    // The non-pinned today thread still falls into Today
    expect(groups.find((g) => g.key === "today")?.threads.map((t) => t.id)).toEqual(["1"])
  })

  it("preserves input order within a bucket (server already sorted)", () => {
    // Server returns lastMessageAt desc; grouper must NOT re-sort
    const t1 = thread({ id: "newer", lastMessageAt: "2026-04-15T13:00:00" })
    const t2 = thread({ id: "older", lastMessageAt: "2026-04-15T08:00:00" })
    const groups = groupThreads([t1, t2])
    expect(groups[0].threads.map((t) => t.id)).toEqual(["newer", "older"])
  })

  it("emits groups in canonical order", () => {
    const fixtures = [
      thread({ id: "today",     lastMessageAt: "2026-04-15T09:00:00" }),
      thread({ id: "yesterday", lastMessageAt: "2026-04-14T18:00:00" }),
      thread({ id: "prev7",     lastMessageAt: "2026-04-11T12:00:00" }),
      thread({ id: "prev30",    lastMessageAt: "2026-04-01T12:00:00" }),
      thread({ id: "older",     lastMessageAt: "2026-02-14T12:00:00" }),
      thread({ id: "pinned",    lastMessageAt: "2025-01-01T00:00:00", pinned: true }),
    ]
    const groups = groupThreads(fixtures)
    expect(groups.map((g) => g.key)).toEqual([
      "pinned", "today", "yesterday", "prev7", "prev30", "older",
    ])
  })

  it("omits empty groups (no Yesterday bucket if no threads from yesterday)", () => {
    const t = thread({ id: "1", lastMessageAt: "2026-04-15T09:00:00" })
    const keys = groupThreads([t]).map((g) => g.key)
    expect(keys).toEqual(["today"])
    expect(keys).not.toContain("yesterday")
  })
})

describe("formatRelativeShort", () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date("2026-04-15T14:00:00"))
  })
  afterEach(() => {
    vi.useRealTimers()
  })

  it("returns 'now' under a minute", () => {
    expect(formatRelativeShort("2026-04-15T13:59:30")).toBe("now")
  })
  it("returns minutes for under an hour", () => {
    expect(formatRelativeShort("2026-04-15T13:45:00")).toBe("15m")
  })
  it("returns hours for same-day", () => {
    expect(formatRelativeShort("2026-04-15T11:00:00")).toBe("3h")
  })
  it("returns 'yesterday' for calendar-yesterday dates older than 24h", () => {
    // The function falls through to "Nh" for anything under 24h, then
    // switches to "yesterday" once we cross into the 24-48h range while
    // still being on the previous calendar day.
    // now: 2026-04-15T14:00; dt: 2026-04-14T08:00 = 30h ago.
    expect(formatRelativeShort("2026-04-14T08:00:00")).toBe("yesterday")
  })

  it("prefers 'Nh' over 'yesterday' for under-24h diffs", () => {
    // Even if the timestamp is on the previous calendar day, under 24h
    // diffs stay as hours — clearer signal for the user.
    // now: 2026-04-15T14:00; dt: 2026-04-14T18:00 = 20h ago.
    expect(formatRelativeShort("2026-04-14T18:00:00")).toBe("20h")
  })
  it("returns 'Mon DD' for same-year older dates", () => {
    expect(formatRelativeShort("2026-03-20T12:00:00")).toMatch(/Mar 20/)
  })
  it("returns 'Mon YYYY' for cross-year older dates", () => {
    expect(formatRelativeShort("2024-08-15T12:00:00")).toMatch(/Aug 2024/)
  })
})
