import { describe, it, expect } from "vitest"
import { parseSseFrame, createSseBuffer } from "./sse-parser"

describe("parseSseFrame", () => {
  it("parses a meta event", () => {
    const frame = `event: meta\ndata: {"userMessageId":"u_1","assistantMessageId":"a_1","contextAvailable":true}`
    const evt = parseSseFrame(frame)
    expect(evt).toEqual({
      type: "meta",
      userMessageId: "u_1",
      assistantMessageId: "a_1",
      contextAvailable: true,
    })
  })

  it("parses a delta event", () => {
    const frame = `event: delta\ndata: {"content":"hello"}`
    expect(parseSseFrame(frame)).toEqual({ type: "delta", content: "hello" })
  })

  it("coerces missing delta content to empty string", () => {
    const frame = `event: delta\ndata: {}`
    expect(parseSseFrame(frame)).toEqual({ type: "delta", content: "" })
  })

  it("parses a done event with message + thread", () => {
    const frame = `event: done\ndata: ${JSON.stringify({
      message: { id: "a_1", role: "ASSISTANT", content: "ok" },
      thread: { id: "t_1", title: "x", titleAutoGenerated: true, lastMessageAt: "2026-04-16T15:00:00Z" },
    })}`
    const evt = parseSseFrame(frame)
    expect(evt?.type).toBe("done")
    if (evt?.type === "done") {
      expect(evt.message.id).toBe("a_1")
      expect(evt.thread.id).toBe("t_1")
    }
  })

  it("returns null for done without message or thread", () => {
    const frame = `event: done\ndata: {"message": {"id":"a_1"}}`
    expect(parseSseFrame(frame)).toBeNull()
  })

  it("parses an error event", () => {
    const frame = `event: error\ndata: {"error":"boom","assistantMessageId":"a_1"}`
    expect(parseSseFrame(frame)).toEqual({
      type: "error",
      error: "boom",
      assistantMessageId: "a_1",
    })
  })

  it("falls back error message when missing", () => {
    const frame = `event: error\ndata: {}`
    expect(parseSseFrame(frame)).toEqual({
      type: "error",
      error: "Unknown error",
      assistantMessageId: undefined,
    })
  })

  it("returns null for unknown event names (forward-compat)", () => {
    const frame = `event: someFutureEvent\ndata: {"x":1}`
    expect(parseSseFrame(frame)).toBeNull()
  })

  it("returns null for malformed JSON", () => {
    const frame = `event: delta\ndata: {not-json`
    expect(parseSseFrame(frame)).toBeNull()
  })

  it("returns null when event line is missing", () => {
    expect(parseSseFrame(`data: {"content":"hi"}`)).toBeNull()
  })

  it("returns null when data line is missing", () => {
    expect(parseSseFrame(`event: delta`)).toBeNull()
  })

  it("ignores SSE comment lines (lines starting with :)", () => {
    const frame = `: heartbeat\nevent: delta\ndata: {"content":"keepalive"}`
    expect(parseSseFrame(frame)).toEqual({ type: "delta", content: "keepalive" })
  })

  it("re-joins multi-line data per RFC", () => {
    const frame = `event: delta\ndata: {"content":\ndata: "two lines"}`
    expect(parseSseFrame(frame)).toEqual({ type: "delta", content: "two lines" })
  })

  it("handles missing space after data:", () => {
    // SSE spec says the space is optional
    const frame = `event: delta\ndata:{"content":"no-space"}`
    expect(parseSseFrame(frame)).toEqual({ type: "delta", content: "no-space" })
  })

  it("rejects meta event missing required IDs", () => {
    const frame = `event: meta\ndata: {"userMessageId":"u_1"}`
    expect(parseSseFrame(frame)).toBeNull()
  })

  it("coerces contextAvailable falsy values to false", () => {
    const frame = `event: meta\ndata: {"userMessageId":"u","assistantMessageId":"a"}`
    const evt = parseSseFrame(frame)
    expect(evt?.type).toBe("meta")
    if (evt?.type === "meta") expect(evt.contextAvailable).toBe(false)
  })
})

describe("createSseBuffer", () => {
  it("yields events as frames complete", () => {
    const buf = createSseBuffer()
    const out1 = buf.push(`event: delta\ndata: {"content":"hi"}\n\n`)
    expect(out1).toHaveLength(1)
    expect(out1[0]).toEqual({ type: "delta", content: "hi" })
  })

  it("buffers across chunk boundaries", () => {
    const buf = createSseBuffer()
    expect(buf.push(`event: delta\n`)).toEqual([])
    expect(buf.push(`data: {"content":"piece"}`)).toEqual([])
    expect(buf.push(`\n\n`)).toEqual([{ type: "delta", content: "piece" }])
  })

  it("yields multiple frames in one chunk", () => {
    const buf = createSseBuffer()
    const events = buf.push(
      `event: meta\ndata: {"userMessageId":"u","assistantMessageId":"a","contextAvailable":true}\n\n` +
      `event: delta\ndata: {"content":"hello"}\n\n`
    )
    expect(events).toHaveLength(2)
    expect(events[0].type).toBe("meta")
    expect(events[1].type).toBe("delta")
  })

  it("keeps trailing partial frame in leftover()", () => {
    const buf = createSseBuffer()
    buf.push(`event: delta\ndata: {"content":"complete"}\n\nevent: delta\ndata: {"con`)
    expect(buf.leftover()).toBe(`event: delta\ndata: {"con`)
  })

  it("skips frames the parser rejects without breaking the stream", () => {
    const buf = createSseBuffer()
    const events = buf.push(
      `event: garbage\ndata: {}\n\n` +
      `event: delta\ndata: {"content":"after-garbage"}\n\n`
    )
    expect(events).toEqual([{ type: "delta", content: "after-garbage" }])
  })
})
