/**
 * Pure SSE frame parser for the Junebug send-message stream
 * (spec §6.6). Lives in its own module so it can be unit-tested
 * without dragging in React, the fetch hook, or the rest of the
 * client surface.
 *
 * Wire format per the spec:
 *
 *     event: meta
 *     data: {"userMessageId": "...", "assistantMessageId": "...", "contextAvailable": true}
 *
 *     event: delta
 *     data: {"content": "partial text..."}
 *
 *     event: done
 *     data: {"message": {...}, "thread": {...}}
 *
 *     event: error
 *     data: {"error": "...", "assistantMessageId": "..."}
 *
 * Frames are blank-line delimited (\n\n per RFC 8895). Stream
 * boundaries don't necessarily align with frame boundaries — the
 * caller is responsible for buffering bytes until \n\n is found.
 *
 * This parser is forgiving: unknown event names return null,
 * malformed JSON returns null, missing fields return null. Never
 * throws. The caller treats null as "skip this frame and keep
 * reading" rather than "tear down the connection."
 */

import type { JunebugMessage, JunebugThreadDetail } from "../types"

export type SendStreamEvent =
  | { type: "meta"; userMessageId: string; assistantMessageId: string; contextAvailable: boolean }
  | { type: "delta"; content: string }
  | {
      type: "done"
      message: JunebugMessage
      thread: Pick<JunebugThreadDetail, "id" | "title" | "titleAutoGenerated"> & {
        lastMessageAt: string
      }
    }
  | { type: "error"; error: string; assistantMessageId?: string }

/**
 * Parse a single SSE frame string (between two `\n\n` boundaries) into
 * a typed event. Returns null if:
 *   - the frame has no `event:` line
 *   - the frame has no `data:` line
 *   - the data isn't valid JSON
 *   - the event name isn't one we know
 *
 * The `data:` body may span multiple lines per RFC; we re-join them
 * with `\n` before parsing.
 */
export function parseSseFrame(frame: string): SendStreamEvent | null {
  const lines = frame.split("\n")
  let eventName: string | null = null
  const dataLines: string[] = []

  for (const line of lines) {
    if (line.startsWith(":")) continue // SSE comment line
    if (line.startsWith("event:")) {
      eventName = line.slice(6).trim()
    } else if (line.startsWith("data:")) {
      // The space after "data:" is optional per spec; trimStart handles both.
      dataLines.push(line.slice(5).trimStart())
    }
  }

  if (!eventName || dataLines.length === 0) return null

  let data: any
  try {
    data = JSON.parse(dataLines.join("\n"))
  } catch {
    return null
  }

  switch (eventName) {
    case "meta":
      if (typeof data.userMessageId !== "string" || typeof data.assistantMessageId !== "string") {
        return null
      }
      return {
        type: "meta",
        userMessageId: data.userMessageId,
        assistantMessageId: data.assistantMessageId,
        contextAvailable: !!data.contextAvailable,
      }
    case "delta":
      return { type: "delta", content: String(data.content ?? "") }
    case "done":
      if (!data.message || !data.thread) return null
      return { type: "done", message: data.message, thread: data.thread }
    case "error":
      return {
        type: "error",
        error: String(data.error ?? "Unknown error"),
        assistantMessageId:
          typeof data.assistantMessageId === "string" ? data.assistantMessageId : undefined,
      }
    default:
      return null
  }
}

/**
 * Stateful chunk buffer — fold streaming bytes into completed frames.
 * Returns the list of completed frames and keeps any trailing partial
 * frame for the next call.
 *
 * Usage:
 *
 *   const buffer = createSseBuffer()
 *   while (true) {
 *     const { done, value } = await reader.read()
 *     if (done) break
 *     for (const evt of buffer.push(decoder.decode(value, { stream: true }))) {
 *       handle(evt)
 *     }
 *   }
 */
export function createSseBuffer() {
  let buffer = ""
  return {
    push(chunk: string): SendStreamEvent[] {
      buffer += chunk
      const events: SendStreamEvent[] = []
      let sep: number
      while ((sep = buffer.indexOf("\n\n")) !== -1) {
        const frame = buffer.slice(0, sep)
        buffer = buffer.slice(sep + 2)
        const evt = parseSseFrame(frame)
        if (evt) events.push(evt)
      }
      return events
    },
    /** Bytes still buffered (no \n\n seen yet). For diagnostics only. */
    leftover(): string {
      return buffer
    },
  }
}
