"use client"

/**
 * useSendMessage — POST a user turn, parse the named-event SSE stream, and
 * feed updates back into the parent's message state.
 *
 * Spec §6.6 / §7.9. Events are:
 *   event: meta    {userMessageId, assistantMessageId, contextAvailable}
 *   event: delta   {content}
 *   event: done    {message, thread}
 *   event: error   {error, assistantMessageId}
 *
 * The SSE wire format is `event: <name>\ndata: <json>\n\n`. We parse by
 * splitting the decoded buffer on blank-line boundaries (per RFC) and
 * reading the first `event:` + `data:` line of each block.
 *
 * The hook does NOT own the message list — it just calls back into
 * useThread's setters (appendMessage / patchMessage). This keeps the list
 * the single source of truth and avoids duplicate optimistic state.
 */

import { useCallback, useRef, useState } from "react"
import type { JunebugMessage, SendMessageInput } from "../types"
import { parseSseFrame, type SendStreamEvent } from "../lib/sse-parser"

interface UseSendMessageCallbacks {
  /** Append a locally-built placeholder USER message immediately on submit. */
  appendUserOptimistic: (msg: JunebugMessage) => void
  /** Replace optimistic USER id with the server's real id once `meta` arrives. */
  reconcileUserMessageId: (optimisticId: string, realId: string) => void
  /** Insert the streaming ASSISTANT placeholder once `meta` arrives. */
  appendAssistantPlaceholder: (msg: JunebugMessage) => void
  /** Append a delta to the streaming assistant message. */
  appendDelta: (assistantId: string, delta: string) => void
  /** Finalize on stream `done`. */
  finalizeAssistant: (msg: JunebugMessage) => void
  /** Persist an error onto the assistant row (and/or mark for retry). */
  markAssistantError: (assistantId: string | undefined, message: string) => void
  /** Bump the thread row (title, lastMessageAt) in the sidebar list. */
  onThreadBumped?: (patch: { id: string; title: string; titleAutoGenerated: boolean; lastMessageAt: string }) => void
}

export function useSendMessage(threadId: string | null, cb: UseSendMessageCallbacks) {
  const [isStreaming, setIsStreaming] = useState(false)
  const [streamError, setStreamError] = useState<string | null>(null)
  const abortRef = useRef<AbortController | null>(null)
  // Serialize turns — Claude.ai behavior (spec §7.9).
  const queueRef = useRef<Promise<void>>(Promise.resolve())

  const abort = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort()
      abortRef.current = null
    }
  }, [])

  const runOne = useCallback(
    async (input: SendMessageInput): Promise<void> => {
      if (!threadId) {
        setStreamError("No active thread")
        return
      }

      const optimisticUserId = `optimistic-${crypto.randomUUID()}`
      const optimisticUser: JunebugMessage = {
        id: optimisticUserId,
        role: "USER",
        content: input.content + (input.attachments?.length
          ? `\n\n[Attached: ${input.attachments.map((a) => a.fileName).join(", ")}]`
          : ""),
        model: null,
        tokensIn: null,
        tokensOut: null,
        durationMs: null,
        contextSnapshot: null,
        errorMessage: null,
        createdAt: new Date().toISOString(),
        attachments: (input.attachments ?? []).map((a, i) => ({
          id: `optimistic-${i}`,
          fileName: a.fileName,
          fileUrl: a.fileUrl,
          fileType: a.fileType,
          fileSize: a.fileSize,
        })),
      }
      cb.appendUserOptimistic(optimisticUser)

      setIsStreaming(true)
      setStreamError(null)
      const ctrl = new AbortController()
      abortRef.current = ctrl

      // We track the assistant ID once meta arrives so deltas have somewhere
      // to land.
      let assistantId: string | null = null
      let accumulated = ""

      try {
        const res = await fetch(`/api/junebug/threads/${threadId}/messages`, {
          method: "POST",
          credentials: "same-origin",
          headers: { "Content-Type": "application/json", Accept: "text/event-stream" },
          body: JSON.stringify(input),
          signal: ctrl.signal,
        })
        if (!res.ok) {
          const text = await res.text().catch(() => "")
          throw new Error(text || `Send failed: ${res.status}`)
        }
        if (!res.body) throw new Error("No response body")

        const reader = res.body.getReader()
        const decoder = new TextDecoder()
        let buffer = ""

        // SSE frames are delimited by \n\n (blank line). Parse as we go.
        while (true) {
          const { done, value } = await reader.read()
          if (done) break
          buffer += decoder.decode(value, { stream: true })

          let sep: number
          while ((sep = buffer.indexOf("\n\n")) !== -1) {
            const frame = buffer.slice(0, sep)
            buffer = buffer.slice(sep + 2)
            const evt = parseSseFrame(frame)
            if (!evt) continue

            switch (evt.type) {
              case "meta": {
                assistantId = evt.assistantMessageId
                cb.reconcileUserMessageId(optimisticUserId, evt.userMessageId)
                cb.appendAssistantPlaceholder({
                  id: evt.assistantMessageId,
                  role: "ASSISTANT",
                  content: "",
                  model: null,
                  tokensIn: null,
                  tokensOut: null,
                  durationMs: null,
                  contextSnapshot: null,
                  errorMessage: null,
                  createdAt: new Date().toISOString(),
                  attachments: [],
                  streaming: true,
                })
                break
              }
              case "delta": {
                if (!assistantId) break
                accumulated += evt.content
                cb.appendDelta(assistantId, evt.content)
                break
              }
              case "done": {
                cb.finalizeAssistant({ ...evt.message, streaming: false })
                cb.onThreadBumped?.({
                  id: evt.thread.id,
                  title: evt.thread.title,
                  titleAutoGenerated: evt.thread.titleAutoGenerated,
                  lastMessageAt: evt.thread.lastMessageAt,
                })
                break
              }
              case "error": {
                cb.markAssistantError(evt.assistantMessageId, evt.error)
                setStreamError(evt.error)
                break
              }
            }
          }
        }
      } catch (err: any) {
        if (err?.name === "AbortError") {
          // User navigated away mid-stream. Save what we have.
          cb.markAssistantError(
            assistantId ?? undefined,
            accumulated
              ? "Connection interrupted"
              : "Send cancelled before a response arrived"
          )
          return
        }
        setStreamError(err?.message || "Send failed")
        cb.markAssistantError(assistantId ?? undefined, err?.message || "Send failed")
      } finally {
        setIsStreaming(false)
        abortRef.current = null
      }
    },
    [threadId, cb]
  )

  const send = useCallback(
    (input: SendMessageInput) => {
      // Queue serially so two rapid sends don't interleave (§7.9).
      const next = queueRef.current.then(() => runOne(input))
      // Swallow errors in the chain so subsequent turns can still run
      queueRef.current = next.catch(() => {})
      return next
    },
    [runOne]
  )

  return { send, isStreaming, streamError, abort }
}
