-- Add new playbook-specific task types to AITaskType enum
ALTER TYPE "AITaskType" ADD VALUE 'IA_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE 'CNC_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE 'TFRP_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE 'INNOCENT_SPOUSE_ANALYSIS';
