-- Add new playbook-specific task types to AITaskType enum
ALTER TYPE "AITaskType" ADD VALUE IF NOT EXISTS 'IA_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE IF NOT EXISTS 'CNC_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE IF NOT EXISTS 'TFRP_ANALYSIS';
ALTER TYPE "AITaskType" ADD VALUE IF NOT EXISTS 'INNOCENT_SPOUSE_ANALYSIS';
