"use client"

/**
 * ThreadView (spec §7.5).
 *
 *   - Top: ThreadContextChip
 *   - Middle: MessageList (scrollable)
 *   - Bottom: MessageComposer
 *
 * If no thread is active, the parent renders ThreadEmptyState instead —
 * this component assumes activeThreadId is set.
 */

import { useCallback, useEffect, useRef, useState } from "react"
import { useThread } from "./hooks/use-thread"
import { useSendMessage } from "./hooks/use-send-message"
import { MessageList } from "./message-list"
import { MessageComposer, type ComposerAttachment } from "./message-composer"
import { ThreadContextChip } from "./thread-context-chip"
import type { JunebugMessage, JunebugThreadListItem } from "./types"

export interface ThreadViewProps {
  threadId: string
  currentRoute?: string
  onThreadBumped: (patch: Partial<JunebugThreadListItem> & { id: string }) => void
  /** Optional: auto-send these on mount (splash screen → new thread handoff). */
  initialSendContent?: string
  initialSendAttachments?: ComposerAttachment[]
  /** Armed state of Full Fetch at splash submit time. */
  initialSendFullFetch?: boolean
  /** Called after initialSendContent has been dispatched, so the parent clears it. */
  onInitialSendDispatched?: () => void
}

export function ThreadView({
  threadId,
  currentRoute,
  onThreadBumped,
  initialSendContent,
  initialSendAttachments,
  initialSendFullFetch,
  onInitialSendDispatched,
}: ThreadViewProps) {
  const t = useThread(threadId)
  const [sendError, setSendError] = useState<string | null>(null)

  // Callbacks are referentially stable — wrap in useCallback so the
  // send hook doesn't recreate on every render.
  const appendUserOptimistic = useCallback((msg: JunebugMessage) => {
    t.appendMessage(msg)
  }, [t])

  const reconcileUserMessageId = useCallback(
    (optimisticId: string, realId: string) => {
      t.patchMessage(optimisticId, { id: realId })
    },
    [t]
  )

  const appendAssistantPlaceholder = useCallback((msg: JunebugMessage) => {
    t.appendMessage(msg)
  }, [t])

  // Delta handler uses the functional appendToMessage helper so the
  // stream loop always writes against the latest state (no closure staleness).
  const liveAppendDelta = useCallback(
    (assistantId: string, delta: string) => {
      t.appendToMessage(assistantId, delta)
    },
    [t]
  )

  const finalizeAssistant = useCallback(
    (msg: JunebugMessage) => {
      t.patchMessage(msg.id, {
        ...msg,
        streaming: false,
      })
    },
    [t]
  )

  const markAssistantError = useCallback(
    (assistantId: string | undefined, message: string) => {
      if (assistantId) {
        t.patchMessage(assistantId, {
          errorMessage: message,
          streaming: false,
        })
      }
      setSendError(message)
    },
    [t]
  )

  const onThreadBumpedCb = useCallback(
    (patch: { id: string; title: string; titleAutoGenerated: boolean; lastMessageAt: string }) => {
      t.patchThread({
        title: patch.title,
        titleAutoGenerated: patch.titleAutoGenerated,
      })
      onThreadBumped(patch)
    },
    [t, onThreadBumped]
  )

  const sender = useSendMessage(threadId, {
    appendUserOptimistic,
    reconcileUserMessageId,
    appendAssistantPlaceholder,
    appendDelta: liveAppendDelta,
    finalizeAssistant,
    markAssistantError,
    onThreadBumped: onThreadBumpedCb,
  })

  const handleSend = useCallback(
    (content: string, attachments: ComposerAttachment[], fullFetch: boolean) => {
      if (!content.trim() && attachments.length === 0) return
      setSendError(null)
      void sender.send({
        content,
        currentRoute,
        fullFetch: fullFetch || undefined,
        attachments: attachments.length
          ? attachments.map((a) => ({
              documentId: a.documentId,
              fileName: a.fileName,
              fileUrl: a.fileUrl,
              fileType: a.fileType,
              fileSize: a.fileSize,
            }))
          : undefined,
      })
    },
    [sender, currentRoute]
  )

  const handleRetry = useCallback(
    async (target: JunebugMessage) => {
      // Only ASSISTANT messages are retryable. Call the regenerate endpoint
      // then re-send the final USER turn.
      if (target.role !== "ASSISTANT") return
      // Find the preceding USER message
      const idx = t.messages.findIndex((m) => m.id === target.id)
      if (idx <= 0) return
      const precedingUser = t.messages[idx - 1]
      if (precedingUser?.role !== "USER") return

      try {
        const res = await fetch(
          `/api/junebug/threads/${threadId}/messages/${target.id}/regenerate`,
          { method: "POST", credentials: "same-origin" }
        )
        if (!res.ok) throw new Error(`Regenerate failed: ${res.status}`)
        // Drop local state from the target forward. The regen API deletes
        // the target and anything later; our optimistic view needs to match.
        t.removeMessagesFrom(target.id)
        // Also drop the preceding USER row — it'll be re-POSTed below so
        // we don't end up with a duplicate. Actually: server kept the USER
        // row; we just need to re-run completion against it. Drop only
        // from target forward AND remove the user row so the new POST can
        // re-add it. Simpler: refetch after the send completes.
        await sender.send({
          content: precedingUser.content,
          currentRoute,
        })
        await t.refetch()
      } catch (err: any) {
        setSendError(err?.message || "Retry failed")
      }
    },
    [t, threadId, sender, currentRoute]
  )

  // Clear transient send error when thread changes
  useEffect(() => {
    setSendError(null)
  }, [threadId])

  // Auto-send the splash-screen message exactly once when this view mounts
  // with `initialSendContent`. Using a ref so StrictMode's double-invoke
  // doesn't fire twice.
  const initialSentRef = useRef(false)
  useEffect(() => {
    if (initialSentRef.current) return
    if (!initialSendContent) return
    initialSentRef.current = true
    handleSend(initialSendContent, initialSendAttachments ?? [], initialSendFullFetch ?? false)
    onInitialSendDispatched?.()
    // Intentionally omitting handleSend from deps — ref guard is the
    // concurrency control. Re-sending on re-render would cause duplicates.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialSendContent])

  // Case-scope mutation. Persists via PATCH /api/junebug/threads/[id] and
  // updates local thread state so the chip reflects the change immediately.
  // Declared BEFORE the early returns below to satisfy rules-of-hooks —
  // hooks must run in the same order on every render.
  const handleCaseChange = useCallback(
    async (caseId: string | null) => {
      const res = await fetch(`/api/junebug/threads/${threadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify({ caseId }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        throw new Error(body?.error || `Failed to update case (${res.status})`)
      }
      const data = await res.json()
      const updated = data.thread
      // Patch local state so the chip's label + metadata refresh without a
      // full refetch. The useThread hook manages its own state.
      t.patchThread({
        caseId: updated.caseId,
        caseNumber: updated.caseNumber,
        clientName: updated.clientName,
      })
    },
    [threadId, t]
  )

  if (t.isLoading && !t.thread) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3 text-c-gray-500">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-c-gray-100 border-t-c-gold" />
        <span className="text-[12px]">Loading conversation…</span>
      </div>
    )
  }

  if (t.error) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-2 px-6 text-center">
        <p className="text-[13px] text-c-danger">{t.error}</p>
        <button
          type="button"
          onClick={() => void t.refetch()}
          className="text-[12px] text-c-gray-500 underline hover:text-c-gray-700"
        >
          Try again
        </button>
      </div>
    )
  }

  return (
    <div className="flex h-full flex-col bg-white">
      <ThreadContextChip
        thread={t.thread}
        messages={t.messages}
        onCaseChange={handleCaseChange}
      />
      {t.messages.length === 0 && !sender.isStreaming ? (
        <div className="flex flex-1 items-center justify-center px-8 py-12 text-center text-c-gray-500">
          <p className="text-[13px]">
            Start the conversation below. Junebug will pull in case context and KB hits automatically.
          </p>
        </div>
      ) : (
        <MessageList
          messages={t.messages}
          isStreaming={sender.isStreaming}
          hasMore={t.hasMore}
          loadingOlder={t.loadingOlder}
          onLoadOlder={() => void t.loadOlder()}
          onRetry={handleRetry}
        />
      )}
      <MessageComposer
        disabled={sender.isStreaming}
        isStreaming={sender.isStreaming}
        onSend={handleSend}
      />
      {sendError && (
        <div className="border-t border-c-danger/20 bg-c-danger/5 px-6 py-2 text-[12px] text-c-danger md:px-10">
          {sendError}
        </div>
      )}
    </div>
  )
}
