/**
 * Client-side types mirroring the Junebug API response shapes (spec §6).
 *
 * Kept in sync with:
 *   - src/app/api/junebug/threads/route.ts
 *   - src/app/api/junebug/threads/[id]/route.ts
 *   - src/app/api/junebug/threads/[id]/messages/route.ts
 */

export type JunebugRole = "USER" | "ASSISTANT" | "SYSTEM"

export interface JunebugAttachment {
  id: string
  fileName: string
  fileUrl: string
  fileType: string
  fileSize: number
}

export interface JunebugMessage {
  id: string
  role: JunebugRole
  content: string
  model: string | null
  tokensIn: number | null
  tokensOut: number | null
  durationMs: number | null
  contextSnapshot: Record<string, any> | null
  errorMessage: string | null
  createdAt: string // ISO
  attachments: JunebugAttachment[]
  /** Transient — set true while the SSE stream is still emitting deltas. */
  streaming?: boolean
}

/** List-item shape returned from GET /api/junebug/threads. */
export interface JunebugThreadListItem {
  id: string
  title: string
  titleAutoGenerated: boolean
  caseId: string | null
  caseNumber: string | null
  clientName: string | null
  pinned: boolean
  archived: boolean
  lastMessageAt: string
  createdAt: string
  messageCount: number
  lastMessagePreview: string
  lastMessageRole: JunebugRole | null
}

/** Detail shape returned from GET /api/junebug/threads/[id]. */
export interface JunebugThreadDetail {
  id: string
  title: string
  titleAutoGenerated: boolean
  caseId: string | null
  caseNumber: string | null
  clientName: string | null
  pinned: boolean
  archived: boolean
  lastMessageAt: string
  createdAt: string
  summary: string | null
}

export interface SendMessageInput {
  content: string
  model?: string
  currentRoute?: string
  pageContext?: unknown
  attachments?: Array<{
    documentId?: string
    fileName: string
    fileUrl: string
    fileType: string
    fileSize: number
  }>
}

/** SSE event shape emitted by POST /api/junebug/threads/[id]/messages. */
export type SendStreamEvent =
  | { type: "meta"; userMessageId: string; assistantMessageId: string; contextAvailable: boolean }
  | { type: "delta"; content: string }
  | { type: "done"; message: JunebugMessage; thread: Pick<JunebugThreadDetail, "id" | "title" | "titleAutoGenerated"> & { lastMessageAt: string } }
  | { type: "error"; error: string; assistantMessageId?: string }
