/**
 * Client-side types mirroring the Junebug API response shapes (spec §6).
 *
 * Kept in sync with:
 *   - src/app/api/junebug/threads/route.ts
 *   - src/app/api/junebug/threads/[id]/route.ts
 *   - src/app/api/junebug/threads/[id]/messages/route.ts
 */

export type JunebugRole = "USER" | "ASSISTANT" | "SYSTEM"

export interface JunebugAttachment {
  id: string
  fileName: string
  fileUrl: string
  fileType: string
  fileSize: number
}

export interface JunebugMessage {
  id: string
  role: JunebugRole
  content: string
  model: string | null
  tokensIn: number | null
  tokensOut: number | null
  durationMs: number | null
  contextSnapshot: Record<string, any> | null
  errorMessage: string | null
  createdAt: string // ISO
  attachments: JunebugAttachment[]
  /** True iff the current practitioner has given this message a treat. */
  treated?: boolean
  /** Optional practitioner note on what they liked about this response. */
  treatNote?: string | null
  /** Transient — set true while the SSE stream is still emitting deltas. */
  streaming?: boolean
}

/** List-item shape returned from GET /api/junebug/threads. */
export interface JunebugThreadListItem {
  id: string
  title: string
  titleAutoGenerated: boolean
  caseId: string | null
  caseNumber: string | null
  clientName: string | null
  pinned: boolean
  archived: boolean
  lastMessageAt: string
  createdAt: string
  messageCount: number
  lastMessagePreview: string
  lastMessageRole: JunebugRole | null
}

/** Detail shape returned from GET /api/junebug/threads/[id]. */
export interface JunebugThreadDetail {
  id: string
  title: string
  titleAutoGenerated: boolean
  caseId: string | null
  caseNumber: string | null
  clientName: string | null
  pinned: boolean
  archived: boolean
  lastMessageAt: string
  createdAt: string
  summary: string | null
}

export interface SendMessageInput {
  content: string
  model?: string
  currentRoute?: string
  pageContext?: unknown
  /**
   * Full Fetch mode — unlocks claude-opus-4-7 at a higher token ceiling,
   * injects the live case data packet (documents with content,
   * liability periods, deadlines, AI work products, client notes), and
   * turns on Vercel log retrieval when the user asks about
   * build/runtime issues.
   */
  fullFetch?: boolean
  attachments?: Array<{
    documentId?: string
    fileName: string
    fileUrl: string
    fileType: string
    fileSize: number
  }>
}

// SSE event shape moved to ../lib/sse-parser.ts (the SendStreamEvent
// type is colocated with the parser that produces it). Import from
// "@/components/junebug/lib/sse-parser" if you need it.
