-- Migration: Junebug Threads (A4.7)
-- Generated: 2026-04-16
--
-- Additions only. Zero destructive changes. All new tables / enums / indexes
-- use IF NOT EXISTS and DO $$ BEGIN ... EXCEPTION WHEN duplicate_object
-- THEN null; END $$ guards so this is safe to run twice.
--
-- Feature is gated behind NEXT_PUBLIC_JUNEBUG_THREADS_ENABLED. When the flag
-- is off, these tables exist but nothing reads or writes to them — zero
-- user-facing change.

-- ============================================================
-- ENUMS
-- ============================================================

DO $$ BEGIN
  CREATE TYPE "JunebugMessageRole" AS ENUM ('USER', 'ASSISTANT', 'SYSTEM');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ============================================================
-- junebug_threads
-- ============================================================

CREATE TABLE IF NOT EXISTS "junebug_threads" (
  "id"                 TEXT NOT NULL,
  "userId"             TEXT NOT NULL,
  "caseId"             TEXT,
  "title"              TEXT NOT NULL,
  "titleAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
  "pinned"             BOOLEAN NOT NULL DEFAULT false,
  "archived"           BOOLEAN NOT NULL DEFAULT false,
  "summary"            TEXT,
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  "lastMessageAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "junebug_threads_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "junebug_threads"
    ADD CONSTRAINT "junebug_threads_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "junebug_threads"
    ADD CONSTRAINT "junebug_threads_caseId_fkey"
    FOREIGN KEY ("caseId") REFERENCES "cases"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "junebug_threads_userId_archived_lastMessageAt_idx"
  ON "junebug_threads" ("userId", "archived", "lastMessageAt" DESC);

CREATE INDEX IF NOT EXISTS "junebug_threads_userId_caseId_archived_idx"
  ON "junebug_threads" ("userId", "caseId", "archived");

CREATE INDEX IF NOT EXISTS "junebug_threads_userId_pinned_archived_idx"
  ON "junebug_threads" ("userId", "pinned", "archived");

-- ============================================================
-- junebug_messages
-- ============================================================

CREATE TABLE IF NOT EXISTS "junebug_messages" (
  "id"              TEXT NOT NULL,
  "threadId"        TEXT NOT NULL,
  "role"            "JunebugMessageRole" NOT NULL,
  "content"         TEXT NOT NULL,
  "model"           TEXT,
  "tokensIn"        INTEGER,
  "tokensOut"       INTEGER,
  "durationMs"      INTEGER,
  "contextSnapshot" JSONB,
  "errorMessage"    TEXT,
  "createdAt"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "junebug_messages_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "junebug_messages"
    ADD CONSTRAINT "junebug_messages_threadId_fkey"
    FOREIGN KEY ("threadId") REFERENCES "junebug_threads"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "junebug_messages_threadId_createdAt_idx"
  ON "junebug_messages" ("threadId", "createdAt");

-- Full-text search index on message content (spec §6.1.1).
-- Lets GET /api/junebug/threads?search=... use to_tsvector / ts_rank_cd
-- against the practitioner's own thread corpus.
CREATE INDEX IF NOT EXISTS "junebug_messages_content_fts"
  ON "junebug_messages"
  USING GIN (to_tsvector('english', "content"));

-- ============================================================
-- junebug_attachments
-- ============================================================

CREATE TABLE IF NOT EXISTS "junebug_attachments" (
  "id"         TEXT NOT NULL,
  "messageId"  TEXT NOT NULL,
  "documentId" TEXT,
  "fileName"   TEXT NOT NULL,
  "fileUrl"    TEXT NOT NULL,
  "fileType"   TEXT NOT NULL,
  "fileSize"   INTEGER NOT NULL,
  "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "junebug_attachments_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "junebug_attachments"
    ADD CONSTRAINT "junebug_attachments_messageId_fkey"
    FOREIGN KEY ("messageId") REFERENCES "junebug_messages"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "junebug_attachments_messageId_idx"
  ON "junebug_attachments" ("messageId");
