import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { prisma } from "@/lib/db"
import { decryptField } from "@/lib/encryption"
import { requireJunebugSession, requireOwnedThread } from "@/lib/junebug/thread-access"

/**
 * /api/junebug/threads/[id] — GET, PATCH, DELETE (spec §6.3, §6.4, §6.5).
 *
 * All routes gate on feature flag + session + ownership. Another user's
 * thread id returns 404 (not 403) — don't leak existence.
 *
 * DELETE requires the X-Confirm-Delete: true header to prevent accidental
 * calls (spec §6.5). Missing → 400.
 */

// ============================================================
// GET — single thread + message history (paginated backward)
// ============================================================

const MESSAGES_DEFAULT = 100
const MESSAGES_MAX = 500

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  const sp = request.nextUrl.searchParams
  const messagesLimit = clampMessagesLimit(sp.get("messagesLimit"))
  const messagesCursor = sp.get("messagesCursor") || undefined

  const thread = await prisma.junebugThread.findUnique({
    where: { id: params.id },
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
    },
  })
  if (!thread) {
    return new NextResponse(null, { status: 404 })
  }

  // Messages returned most-recent-last (ascending by createdAt). When
  // paginating backward via messagesCursor we return the PAGE BEFORE that
  // cursor — older messages. hasMoreMessages means there's still older
  // content to load.
  const cursorFilter = messagesCursor
    ? { createdAt: { lt: decodeMessageCursor(messagesCursor) } }
    : undefined

  // Fetch limit+1 descending to detect more, then reverse for chronological.
  const raw = await prisma.junebugMessage.findMany({
    where: { threadId: params.id, ...(cursorFilter ?? {}) },
    orderBy: { createdAt: "desc" },
    take: messagesLimit + 1,
    include: {
      attachments: {
        select: {
          id: true,
          fileName: true,
          fileUrl: true,
          fileType: true,
          fileSize: true,
        },
      },
    },
  })

  const hasMoreMessages = raw.length > messagesLimit
  const page = (hasMoreMessages ? raw.slice(0, messagesLimit) : raw).reverse()

  const oldestMessageCursor = hasMoreMessages && page.length > 0
    ? encodeMessageCursor(page[0].createdAt)
    : null

  let clientName: string | null = null
  if (thread.case?.clientName) {
    try {
      clientName = decryptField(thread.case.clientName)
    } catch {
      clientName = null
    }
  }

  return NextResponse.json({
    thread: {
      id: thread.id,
      title: thread.title,
      titleAutoGenerated: thread.titleAutoGenerated,
      caseId: thread.caseId,
      caseNumber: thread.case?.tabsNumber ?? null,
      clientName,
      pinned: thread.pinned,
      archived: thread.archived,
      lastMessageAt: thread.lastMessageAt.toISOString(),
      createdAt: thread.createdAt.toISOString(),
      summary: thread.summary,
    },
    messages: page.map((m) => ({
      id: m.id,
      role: m.role,
      content: m.content,
      model: m.model,
      tokensIn: m.tokensIn,
      tokensOut: m.tokensOut,
      durationMs: m.durationMs,
      contextSnapshot: m.contextSnapshot,
      errorMessage: m.errorMessage,
      createdAt: m.createdAt.toISOString(),
      attachments: m.attachments,
    })),
    hasMoreMessages,
    oldestMessageCursor,
  })
}

// ============================================================
// PATCH — update title / pinned / archived / caseId
// ============================================================

const patchSchema = z
  .object({
    title: z.string().min(1).max(200).optional(),
    pinned: z.boolean().optional(),
    archived: z.boolean().optional(),
    caseId: z.union([z.string().cuid(), z.null()]).optional(),
  })
  .refine((v) => Object.keys(v).length > 0, { message: "no fields to update" })

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  let body: z.infer<typeof patchSchema>
  try {
    body = patchSchema.parse(await request.json())
  } catch (err: any) {
    return NextResponse.json(
      { error: "Invalid body", detail: err?.message },
      { status: 400 }
    )
  }

  // If caseId is being set, verify the case exists
  if (body.caseId) {
    const caseExists = await prisma.case.findUnique({
      where: { id: body.caseId },
      select: { id: true },
    })
    if (!caseExists) {
      return NextResponse.json({ error: "Case not found" }, { status: 404 })
    }
  }

  const data: Record<string, any> = {}
  if (body.title !== undefined) {
    data.title = body.title
    // A user rename locks the title — auto-generation never overwrites it
    data.titleAutoGenerated = false
  }
  if (body.pinned !== undefined) data.pinned = body.pinned
  if (body.archived !== undefined) data.archived = body.archived
  if (body.caseId !== undefined) data.caseId = body.caseId

  const updated = await prisma.junebugThread.update({
    where: { id: params.id },
    data,
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
      _count: { select: { messages: true } },
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { role: true, content: true },
      },
    },
  })

  let clientName: string | null = null
  if (updated.case?.clientName) {
    try {
      clientName = decryptField(updated.case.clientName)
    } catch {
      clientName = null
    }
  }
  const last = updated.messages[0]

  return NextResponse.json({
    thread: {
      id: updated.id,
      title: updated.title,
      titleAutoGenerated: updated.titleAutoGenerated,
      caseId: updated.caseId,
      caseNumber: updated.case?.tabsNumber ?? null,
      clientName,
      pinned: updated.pinned,
      archived: updated.archived,
      lastMessageAt: updated.lastMessageAt.toISOString(),
      createdAt: updated.createdAt.toISOString(),
      messageCount: updated._count.messages,
      lastMessagePreview: last?.content ? last.content.slice(0, 120) : "",
      lastMessageRole: (last?.role as any) ?? null,
    },
  })
}

// ============================================================
// DELETE — permanent, requires X-Confirm-Delete: true
// ============================================================

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const confirm = request.headers.get("x-confirm-delete")
  if (confirm !== "true") {
    return NextResponse.json(
      {
        error: "Missing X-Confirm-Delete: true header",
        hint: "Destructive operation requires explicit confirmation header.",
      },
      { status: 400 }
    )
  }

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  // Cascade handles messages + attachments per the Prisma schema relations
  await prisma.junebugThread.delete({ where: { id: params.id } })

  return new NextResponse(null, { status: 204 })
}

// ============================================================
// Helpers
// ============================================================

function clampMessagesLimit(raw: string | null): number {
  if (!raw) return MESSAGES_DEFAULT
  const n = Number.parseInt(raw, 10)
  if (!Number.isFinite(n) || n < 1) return MESSAGES_DEFAULT
  return Math.min(n, MESSAGES_MAX)
}

function encodeMessageCursor(d: Date): string {
  return Buffer.from(d.toISOString()).toString("base64url")
}

function decodeMessageCursor(raw: string): Date {
  try {
    const iso = Buffer.from(raw, "base64url").toString("utf-8")
    const d = new Date(iso)
    return Number.isNaN(d.getTime()) ? new Date() : d
  } catch {
    return new Date()
  }
}
