import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import * as Sentry from "@sentry/nextjs"
import { prisma } from "@/lib/db"
import { decryptField } from "@/lib/encryption"
import { requireJunebugSession, requireOwnedThread } from "@/lib/junebug/thread-access"
import { createAuditLog, AUDIT_ACTIONS } from "@/lib/ai/audit"

/**
 * Shared 500-handler for the GET / PATCH / DELETE paths below. Captures
 * the exception into Sentry with the right tags, then returns a terse
 * JSON error. NEVER returns err.message to the client (that's where
 * stack-adjacent strings like "connect ECONNREFUSED 10.0.0.1:5432"
 * can leak).
 */
function handle500(
  op: "get" | "patch" | "delete",
  err: unknown,
  ctx: { userId: string; threadId: string }
) {
  Sentry.captureException(err, {
    tags: { route: `junebug/thread/${op}`, junebug: `thread-${op}-failed` },
    user: { id: ctx.userId },
    extra: { threadId: ctx.threadId },
  })
  return NextResponse.json(
    { error: `Failed to ${op} thread` },
    { status: 500 }
  )
}

/**
 * /api/junebug/threads/[id] — GET, PATCH, DELETE (spec §6.3, §6.4, §6.5).
 *
 * All routes gate on feature flag + session + ownership. Another user's
 * thread id returns 404 (not 403) — don't leak existence.
 *
 * DELETE requires the X-Confirm-Delete: true header to prevent accidental
 * calls (spec §6.5). Missing → 400.
 */

// ============================================================
// GET — single thread + message history (paginated backward)
// ============================================================

const MESSAGES_DEFAULT = 100
const MESSAGES_MAX = 500

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  try {
  const sp = request.nextUrl.searchParams
  const messagesLimit = clampMessagesLimit(sp.get("messagesLimit"))
  const messagesCursor = sp.get("messagesCursor") || undefined

  const thread = await prisma.junebugThread.findUnique({
    where: { id: params.id },
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
    },
  })
  if (!thread) {
    return new NextResponse(null, { status: 404 })
  }

  // Messages returned most-recent-last (ascending by createdAt). When
  // paginating backward via messagesCursor we return the PAGE BEFORE that
  // cursor — older messages. hasMoreMessages means there's still older
  // content to load.
  const cursorFilter = messagesCursor
    ? { createdAt: { lt: decodeMessageCursor(messagesCursor) } }
    : undefined

  // Fetch limit+1 descending to detect more, then reverse for chronological.
  // `treats: { where: { userId } }` scopes the nested fetch so we return
  // only the current practitioner's treat on each message — never leak
  // another user's reinforcement signals.
  const raw = await prisma.junebugMessage.findMany({
    where: { threadId: params.id, ...(cursorFilter ?? {}) },
    orderBy: { createdAt: "desc" },
    take: messagesLimit + 1,
    include: {
      attachments: {
        select: {
          id: true,
          fileName: true,
          fileUrl: true,
          fileType: true,
          fileSize: true,
        },
      },
      treats: {
        where: { userId: auth.userId },
        select: { id: true, note: true, createdAt: true },
      },
    },
  })

  const hasMoreMessages = raw.length > messagesLimit
  const page = (hasMoreMessages ? raw.slice(0, messagesLimit) : raw).reverse()

  const oldestMessageCursor = hasMoreMessages && page.length > 0
    ? encodeMessageCursor(page[0].createdAt)
    : null

  let clientName: string | null = null
  if (thread.case?.clientName) {
    try {
      clientName = decryptField(thread.case.clientName)
    } catch {
      clientName = null
    }
  }

  return NextResponse.json({
    thread: {
      id: thread.id,
      title: thread.title,
      titleAutoGenerated: thread.titleAutoGenerated,
      caseId: thread.caseId,
      caseNumber: thread.case?.tabsNumber ?? null,
      clientName,
      pinned: thread.pinned,
      archived: thread.archived,
      lastMessageAt: thread.lastMessageAt.toISOString(),
      createdAt: thread.createdAt.toISOString(),
      summary: thread.summary,
    },
    messages: page.map((m) => ({
      id: m.id,
      role: m.role,
      content: m.content,
      model: m.model,
      tokensIn: m.tokensIn,
      tokensOut: m.tokensOut,
      durationMs: m.durationMs,
      contextSnapshot: m.contextSnapshot,
      errorMessage: m.errorMessage,
      createdAt: m.createdAt.toISOString(),
      attachments: m.attachments,
      // Treat state is per-user. `m.treats` was already filtered by
      // userId above, so this is just "does the current practitioner
      // have one?". The optional note is included so the UI can show
      // it as a tooltip on the bone icon.
      treated: m.treats.length > 0,
      treatNote: m.treats[0]?.note ?? null,
    })),
    hasMoreMessages,
    oldestMessageCursor,
  })
  } catch (err) {
    return handle500("get", err, { userId: auth.userId, threadId: params.id })
  }
}

// ============================================================
// PATCH — update title / pinned / archived / caseId
// ============================================================

const patchSchema = z
  .object({
    title: z.string().min(1).max(200).optional(),
    pinned: z.boolean().optional(),
    archived: z.boolean().optional(),
    caseId: z.union([z.string().cuid(), z.null()]).optional(),
  })
  .refine((v) => Object.keys(v).length > 0, { message: "no fields to update" })

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  let body: z.infer<typeof patchSchema>
  try {
    body = patchSchema.parse(await request.json())
  } catch (err: any) {
    return NextResponse.json(
      { error: "Invalid body", detail: err?.message },
      { status: 400 }
    )
  }

  try {
  // If caseId is being set, verify the case exists
  if (body.caseId) {
    const caseExists = await prisma.case.findUnique({
      where: { id: body.caseId },
      select: { id: true },
    })
    if (!caseExists) {
      return NextResponse.json({ error: "Case not found" }, { status: 404 })
    }
  }

  const data: Record<string, any> = {}
  if (body.title !== undefined) {
    data.title = body.title
    // A user rename locks the title — auto-generation never overwrites it
    data.titleAutoGenerated = false
  }
  if (body.pinned !== undefined) data.pinned = body.pinned
  if (body.archived !== undefined) data.archived = body.archived
  if (body.caseId !== undefined) data.caseId = body.caseId

  const updated = await prisma.junebugThread.update({
    where: { id: params.id },
    data,
    include: {
      case: { select: { tabsNumber: true, clientName: true } },
      _count: { select: { messages: true } },
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { role: true, content: true },
      },
    },
  })

  // Audit — records WHICH fields changed (not the title itself — titles
  // can contain practitioner shorthand that's effectively PII-adjacent).
  createAuditLog({
    practitionerId: auth.userId,
    caseId: updated.caseId ?? undefined,
    action: AUDIT_ACTIONS.JUNEBUG_THREAD_UPDATED,
    metadata: {
      threadId: params.id,
      changedFields: Object.keys(data),
      pinned: typeof body.pinned === "boolean" ? body.pinned : undefined,
      archived: typeof body.archived === "boolean" ? body.archived : undefined,
      retitled: typeof body.title === "string",
      caseReassigned: body.caseId !== undefined,
    },
  }).catch(() => {})

  let clientName: string | null = null
  if (updated.case?.clientName) {
    try {
      clientName = decryptField(updated.case.clientName)
    } catch {
      clientName = null
    }
  }
  const last = updated.messages[0]

  return NextResponse.json({
    thread: {
      id: updated.id,
      title: updated.title,
      titleAutoGenerated: updated.titleAutoGenerated,
      caseId: updated.caseId,
      caseNumber: updated.case?.tabsNumber ?? null,
      clientName,
      pinned: updated.pinned,
      archived: updated.archived,
      lastMessageAt: updated.lastMessageAt.toISOString(),
      createdAt: updated.createdAt.toISOString(),
      messageCount: updated._count.messages,
      lastMessagePreview: last?.content ? last.content.slice(0, 120) : "",
      lastMessageRole: (last?.role as any) ?? null,
    },
  })
  } catch (err) {
    return handle500("patch", err, { userId: auth.userId, threadId: params.id })
  }
}

// ============================================================
// DELETE — permanent, requires X-Confirm-Delete: true
// ============================================================

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const auth = await requireJunebugSession()
  if (!auth.ok) return auth.response

  const confirm = request.headers.get("x-confirm-delete")
  if (confirm !== "true") {
    return NextResponse.json(
      {
        error: "Missing X-Confirm-Delete: true header",
        hint: "Destructive operation requires explicit confirmation header.",
      },
      { status: 400 }
    )
  }

  const access = await requireOwnedThread(params.id, auth.userId)
  if (!access.ok) return access.response

  try {
  // Count messages before delete for the audit record. Forensically
  // useful — "did a practitioner torch 500 messages of work, or just
  // an empty stub thread?"
  const messageCount = await prisma.junebugMessage
    .count({ where: { threadId: params.id } })
    .catch(() => -1)

  // Cascade handles messages + attachments per the Prisma schema relations
  await prisma.junebugThread.delete({ where: { id: params.id } })

  // Audit — permanent deletes are the single most important thing to
  // log. Fire-and-forget; the thread is already gone.
  createAuditLog({
    practitionerId: auth.userId,
    caseId: access.thread.caseId ?? undefined,
    action: AUDIT_ACTIONS.JUNEBUG_THREAD_DELETED,
    metadata: {
      threadId: params.id,
      messageCount,
    },
  }).catch(() => {})

  return new NextResponse(null, { status: 204 })
  } catch (err) {
    return handle500("delete", err, { userId: auth.userId, threadId: params.id })
  }
}

// ============================================================
// Helpers
// ============================================================

function clampMessagesLimit(raw: string | null): number {
  if (!raw) return MESSAGES_DEFAULT
  const n = Number.parseInt(raw, 10)
  if (!Number.isFinite(n) || n < 1) return MESSAGES_DEFAULT
  return Math.min(n, MESSAGES_MAX)
}

function encodeMessageCursor(d: Date): string {
  return Buffer.from(d.toISOString()).toString("base64url")
}

function decodeMessageCursor(raw: string): Date {
  try {
    const iso = Buffer.from(raw, "base64url").toString("utf-8")
    const d = new Date(iso)
    return Number.isNaN(d.getTime()) ? new Date() : d
  } catch {
    return new Date()
  }
}
